### ISSUE TITLE
Update alloyeditor.com site

### ISSUE THREAD

**Issue by jbalsas** [liferay/alloy-editor#1091]
We should update our current site and co-locate it for better traceability and easier maintenance.

The code for the site is currently kept at https://github.com/liferay/alloyeditor.com 

At the same time, we should migrate from our old Electric site to a new one using our Gatsby Boilerplate

**Comment by blzaugg** [comment]
I'd also suggest, keeping the Alloy Editor version, used in the live demos, in sync with the latest release. Currently it uses `v1.5.0` rather than `v1.5.19`.

**Comment by julien** [comment]
@blzaugg yes, that's our plan too

**Comment by wincent** [comment]
Creating https://github.com/liferay/alloy-editor/issues/1161 to track the **content** updates. We'll define what's required and then coordinate with @mwilliams2014 on making sure everything is in place and up-to-scratch.

Leaving this one for any remaining structural/build issues that aren't already covered elsewhere.

**Comment by wincent** [comment]
Going to close this now because it's not specific and actionable enough. We can create tickets for individual stuff that we want done, like [making search work](https://github.com/liferay/alloy-editor/issues/1141), the [aforementioned content updates](https://github.com/liferay/alloy-editor/issues/1161) etc.
