### ISSUE TITLE
Live website demo is not working in IE11

### ISSUE THREAD

**Issue by blzaugg** [liferay/alloy-editor#1227]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The live demo on the website does not work in IE11, and errors in the browser console.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Open IE11 to https://www.alloyeditor.com/
2. Scroll down to inline editor.
3. Attempt to edit content or interact with the editor

**What is the expected behavior?**
Should be able to edit content and interact with the editor.

**Which versions of alloy-editor, and which browser / OS are affected by this issue? Did this work in previous versions?**
Internet Explorer 11 on Windows 7

**Comment by blzaugg** [comment]
![AlloyEditor com in IE11](https://user-images.githubusercontent.com/1626739/56315798-86782280-610d-11e9-9cf8-0302f1315467.gif)

**Comment by wincent** [comment]
Thanks for catching this @blzaugg. Looks like we need to add a polyfill. The website is just including "alloy-editor/alloy-editor-all-min.js" and expecting everything to be rosy but evidently that's not enough.

**Comment by wincent** [comment]
Ok, fix is [now deployed to gh-pages branch](https://github.com/liferay/alloy-editor/commit/caf88fe0b490d9908e3323009f57ea716c1c3ef0). Unfortunately you can't see it on [the live site](https://www.alloyeditor.com/) and in fact the live site is down right now due to a misconfigured CNAME. I've opened an IT ticket to get that fixed.
