### ISSUE TITLE
Idea: Gain feedback from users on what they need from Alloy Editor

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#1380]
This needs to be a moment when users are able to direct the features and abilities of Alloy Editor. They are the people using this editor every day, what do they need, what are their issues?

**Comment by wincent** [comment]
Please feel free to create specific issues for any needs that aren't being fulfilled or problems that you are running into, @duracell80. Same goes for anybody else reading this: the issue tracker is open and submissions are welcome.

I'm going to close this one though because it is not immediately actionable for us — at the moment we're happy with this passive communication channel in which people can freely contribute feedback as they see fit. In the meantime, let's keep the issue tracker for specific, actionable feedback (bug reports and feature requests). We feel that's the most suitable use for this platform, because the audience (developers) operates in those terms (bugs + features).
