### ISSUE TITLE
Table toolbar is not visible in case of many rows

### ISSUE THREAD

**Issue by rolandpakai** [liferay/alloy-editor#1403]
The table toolbar is not visible if the top of the table is not visible when a table is created with many rows.

Reproduction steps:

Make a table that has 50 rows and 3 columns
Scroll down to the last row of the table and click on it
Expected:
The Table toolbar to add/remove rows/columns/cells to appear top-center of the cell

Actual behavior
The toolbar appears, but it's not visible. In fact, it will be at the very top-center of the table

It is reproducable on the AlloyEditor demo @ https://alloyeditor.com/

The customer ticket: https://liferay-support.zendesk.com/agent/tickets/26861
The TSE ticket: https://issues.liferay.com/browse/LPP-37979
My investigatiion: https://issues.liferay.com/browse/LPP-37979?focusedCommentId=2188689&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2188689

**Comment by rolandpakai** [comment]
Hi @wincent 

could you please let me known when will be this released?

Thanks, Roland

**Comment by wincent** [comment]
@julien Do we have anything else pending before we release? We merged the CKEditor update; not sure if anything else in the queue (I don't think there is). Releasing is pretty easy (takes about half an hour), so I imagine we can do it in the next few days. Risk seems low, despite being right in the GA release window. Thoughts, Julien?

I created https://issues.liferay.com/browse/LPS-116520 to track updating in liferay-portal, so that is a ticket you can watch if you don't want to watch this repo instead.

![why-not-both](https://user-images.githubusercontent.com/7074/86363265-df7e9880-bc76-11ea-85c7-60b41eaa92d2.gif)

**Comment by julien** [comment]
@wincent we don't have anything else pending before we release.
I also think the risk is low despite the GA release being soon.

**Comment by julien** [comment]
Well seeing that I can do this now, I'm going to prepare a release
