### ISSUE TITLE
CK Editor 4 supported to 2023

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#1421]
I just caught a git post from 2019 about CK4 ...

"As for CKEditor 4: the official support for CKEditor 4 is until 2023. This is something that we committed to already, and for sure we will not end up the support earlier than that."

Was there any progress in getting off of CK4 onto 5 in DXP? And can Tiny MCE be brought back into DXP?

**Comment by wincent** [comment]
> Was there any progress in getting off of CK4 onto 5 in DXP?

To my knowledge, no change since prior discussions:

- [LPS-83721](https://issues.liferay.com/browse/LPS-83731)
- [LPS-83732](https://issues.liferay.com/browse/LPS-83732)

The hard blocker there which seems very unlikely to change (at least, unlikely to change due to action on _our_ part) is the licensing issue, which is that CKEditor 5 is [GPL >= v2](https://github.com/ckeditor/ckeditor5/blob/master/LICENSE.md), which is compatible with the Community Edition but not with the code in DXP, which is currently subject to the [Liferay Enterprise Subscription License](https://github.com/liferay/liferay-portal/blob/9c9f997c43737dc85a9ff9f960c6359a056e4c91/modules/dxp/copyright.js).

Unless something changes about licensing, we'll continue to use CKEditor v4, and maintain whatever patches are necessary to it (on our [liferay-ckeditor fork](https://github.com/liferay/liferay-ckeditor)) even after v4 officially drops upstream support.

And if the licensing changes on either the CKEditor or the DXP side such that they become compatible again, we'd definitely explore moving to v5. We'd obviously need to evaluate the compatibility matrix again at that point in time; for example, moving to v5 would also be contingent on IE11 no longer being in the Liferay compatibility matrix, seeing as v5 doesn't support IE.

> And can Tiny MCE be brought back into DXP?

I don't know the answer to that one (although I suspect that the reasoning for removing — see [LPS-110733](https://issues.liferay.com/browse/LPS-110733) — it like we did a few months ago hasn't changed at all since April, so I am skeptical that we'd reverse course on that one), but I do know that it would probably be more appropriate to discuss it in an LPS than on the AlloyEditor repo.

Going to close this one as answered (the CKEditor v4 bit), and we can continue the discussion about TinyMCE elsewhere if you want (LPS-110733 would probably be a good place to comment).
