### ISSUE TITLE
Toolbar is hidden when using inside a modal

### ISSUE THREAD

**Issue by brunocoelho** [liferay/alloy-editor#162]
Hey guys, I'm trying to use AlloyEditor inside a modal but the toolbar is hidden due to modal's z-index.
To workaround this problem I had to put a z-index in `.alloy-editor-toolbar` higher than the modal.
Is there anything you can do on AlloyEditor's side or it has to be solved on my side?

![screen shot 2015-04-07 at 9 34 13 am](https://cloud.githubusercontent.com/assets/827445/7023201/9e4e6ad6-dd09-11e4-8208-7dd2f4476984.png)

**Comment by ipeychev** [comment]
Hey Bruno,

We can set explicitly a z-index on this class, but the point is that this may or may not work. Even if you set z-index to 9999 for example, it cannot be guaranteed that in some App there won't be even bigger z-index somewhere.
Even worst situation could be when in some App there are two modal dialogs on top on each other. If we set z-index to 9999 for example, the Toolbar will appear on top of everything, but actually it shouldn't - it should appear above the first and below the second dialog. This entirely depends on the App and there is no way for us to know what to do. In Portal for example there is a special system for controlling the z-indexes (which I wrote) - this should hint you that dealing with these z-indexes is not so simple task.

In general, there is no good way to fix this issue - the only option for us is to set big enough z-index but even in this case it may not work, that's why we left this to App developers.

Hope that helps and if you have an idea how to fix this is more clever way I'm all in ears!

Thanks,
