### ISSUE TITLE
How do Twitter links work?

### ISSUE THREAD

**Issue by dandv** [liferay/alloy-editor#227]
I was somewhat confused by the demo re. entering Twitter links. I thought Alloy would expand Twitter links into tweets, as you see on some news sites. So I pasted a link like "https://twitter.com/BreakingNews/status/605224387260903425", which got hyperlinked, but nothing Twitter-specific happened.

It would help clear the confusion to perhaps link the text about Twitter links to [its demo](http://alloyeditor.com/features/twitter/).

**Comment by jbalsas** [comment]
Hey @dandv 

Sorry about the confusion... do you think it's clear enough in the [Twitter Button demo](http://alloyeditor.com/features/twitter/)? 

Maybe we could reword the sentence in the demo to something like: _Add twitable links_ or _Generate twitter links_

The other thing you mention (which we're calling paste handlers) is in our shortlist :wink:

**Comment by duracell80** [comment]
As I see it: This is a twitter status update, it posts the selected text into a status box so that it can be "re-tweeted" via the users logged in account but the tweet is never linked back to the source site via a (bug report needed). Twitter now automatically shortens URL's in status updates : https://www.lifewire.com/make-short-urls-on-twitter-3476762 

This functionality is not very well explained or intuitive and the icon could be better represented with an arrow based icon inside a bird. Also users may want to "re-blog" or "re-pin" instead.

Maybe the OP is thinking of Twitter Cards?
