### ISSUE TITLE
Cleanup / what are minimum necessary files for AlloyEditor standalone with a UI?

### ISSUE THREAD

**Issue by dandv** [liferay/alloy-editor#229]
I'm considering deploying Alloy in a lower-bandwidth environment, and load time is important. My project doesn't use React or CKEditor, so I have to load those.

What are the minimum files that Alloy needs? The ZIP downloadable from [the guide](http://alloyeditor.com/guides/how_to_use_it/) includes files from CKEditor, like dialog_ie7.css and dialog_ie8.css, despite the README stating only IE9+ is supported.

The lang directory includes both `XX.js` and `alloy-editor/XX.js`. Can we get rid of one set?

Fonts include alloyeditor.eot, which is only useful for IE8 or older, and an SVG font, which is useful on iOS 5 or older, which has a [<1% market share](https://developer.apple.com/support/appstore/).

Do we need images like `skins/moono/images/close.png` or `lock.png`, for which there are [Unicode characters](http://www.fileformat.info/info/unicode/char/1f512/index.htm)? Some of these icons are also included in [the font](https://github.com/liferay/alloy-editor/tree/master/dist/alloy-editor/assets/fonts).

With the files in the screenshot, I could take the size down to 800K minified, but that's a little too large for my project.

![image](https://cloud.githubusercontent.com/assets/33569/7906726/7342fb58-07e4-11e5-8066-60a9879c4929.png)

**Comment by ipeychev** [comment]
Hello,
 
> I'm considering deploying Alloy in a lower-bandwidth environment, and load time is important. My project doesn't use React or CKEditor, so I have to load those.

> What are the minimum files that Alloy needs? The ZIP downloadable from the guide includes files from CKEditor, like dialog_ie7.css and dialog_ie8.css, despite the README stating only IE9+ is supported.

What I would do in production mode is exactly what is written [here](http://alloyeditor.com/guides/):
- I would include the CSS and JS of AlloyEditor:
```html
<link href="alloy-editor/assets/alloy-editor-ocean-min.css" rel="stylesheet">
<script src="alloy-editor/alloy-editor-all-min.js"></script>
```
This is everything you need to make it working.

> The lang directory includes both XX.js and alloy-editor/XX.js. Can we get rid of one set?

We don't use CKEditor's language format, because the strings are grouped by plugins. We have our own format.
The language files for CKEditor, among with its config and other files are here for only one reason - to alloy people who already use CKEditor in their projects to continue do it and use AlloyEditor in the same case. I wish we could get rid of them.

Loading AlloyEditor language files:
- When some user navigates to a page, when AlloyEditor is enabled, the editor will detect the used language and it will make a separate request to load the corresponding language file. If the language cannot be recognized, the default language - English will be used.
- If you want to avoid this separate request (for example because you want to provide only English support) or better - because you are smart and you are detecting the language on the server and you know it already when you are constructing the page, then load AlloyEditor's language file on the page and just include it after its main script. The editor will use it and it will not do an additional request.

> Fonts include alloyeditor.eot, which is only useful for IE8 or older, and an SVG font, which is useful on iOS 5 or older, which has a <1% market share.

These we generate automatically and the browser is requesting what it understands. We can get rid of these, and I will take a note here, but they are not important and they will not cause performance penalties.

> Do we need images like skins/moono/images/close.png or lock.png, for which there are Unicode characters? Some of these icons are also included in the font.

No, we don't. They are for CKEditor. They will be not loaded, when you use only AlloyEditor in your project.

> With the files in the screenshot, I could take the size down to 800K minified, but that's a little too large for my project.

The total size of the downloaded files will be:
- alloy-editor-ocean-min.css - about **3.5kb**
- alloy-editor-all-min.js - about **175kb**
- the language file -  about **1kb**

As you see, this is less than 180Kb. In comparison, the OOTB CKEditor loads more. Since we don't use their UI, but only the engine, we load less.

**Comment by dandv** [comment]
> What I would do in production mode is exactly what is written here:

> I would include the CSS and JS of AlloyEditor:
> <link href="alloy-editor/assets/alloy-editor-ocean-min.css" rel="stylesheet">
> <script src="alloy-editor/alloy-editor-all-min.js"></script>
> This is everything you need to make it working.

I've done just that, but the JS refers to the moono skin, so that needs to be taken into account. If I move away the `skins` directory, I get this error:

![image](https://cloud.githubusercontent.com/assets/33569/7909897/d0c86658-0804-11e5-93ec-1892bc4e55a5.png)

> CKEDITOR.tools.extend.append @ alloy-editor-all-min.js:77CKEDITOR.tools.extend.appendStyleSheet @ alloy-editor-all-min.js:66b @ alloy-editor-all-min.js:458CKEDITOR.skin.loadPart @ alloy-editor-all-min.js:460k @ alloy-editor-all-min.js:237(anonymous function) @ alloy-editor-all-min.js:237j @ alloy-editor-all-min.js:10CKEDITOR.event.CKEDITOR.event.fire @ alloy-editor-all-min.js:12CKEDITOR.editor.CKEDITOR.editor.fire @ alloy-editor-all-min.js:13CKEDITOR.event.CKEDITOR.event.fireOnce @ alloy-editor-all-min.js:12CKEDITOR.editor.CKEDITOR.editor.fireOnce @ alloy-editor-all-min.js:13d @ alloy-editor-all-min.js:235(anonymous function) @ alloy-editor-all-min.js:235CKEDITOR.scriptLoader.queue.c.push.callback @ alloy-editor-all-min.js:223CKEDITOR.scriptLoader.load.m @ alloy-editor-all-min.js:221CKEDITOR.scriptLoader.load.y @ alloy-editor-all-min.js:221CKEDITOR.scriptLoader.load.s @ alloy-editor-all-min.js:221(anonymous function) @ alloy-editor-all-min.js:222

**Comment by ipeychev** [comment]
Yes, this is a file which CKEditor requires and tries to load. I have this issue in my queue but when I looked on it, I didn't discover a way to prevent loading on this file without breaking CKEditor or modifying its sources.

The issue that we want to allow users to use both editors on the same page, otherwise I would discard that long time ago. We have to try again, I will leave this issue to take it into account, thanks!
