### ISSUE TITLE
Can't use http://ckeditor.com/addon/uicolor plugin. 

### ISSUE THREAD

**Issue by akaiworld** [liferay/alloy-editor#343]
Can't use http://ckeditor.com/addon/uicolor plugin. Here is my code

AlloyEditor.editable(this, {

extraPlugins: AlloyEditor.Core.ATTRS.extraPlugins.value+

',ae_buttonbridge,ae_panelmenubuttonbridge,ae_richcombobridge,ae_uibridge,dialog,uicolor',//dialog,uicolor

toolbars: {

styles: {

selections: [{

name: 'text',

buttons: [

'bold', 'italic', 'strike', 'underline',

'uicolor',

'linkEdit',

'ul', 'ol',

],

test: AlloyEditor.SelectionTest.text

}]

}

}

});

**Comment by jbalsas** [comment]
Hey @akaiworld, the key to the bridged button would be `UIColor` instead of `uicolor`. That will make it appear on the toolbar. However, our skins do not use CKEditor's `chameleon` so it won't do any changes on the editor's appearance.

Is this exactly what you're trying? Maybe you wanted to use [ColorButton](http://ckeditor.com/addon/colorbutton) instead?

**Comment by akaiworld** [comment]
Used UIColor, button appeared, but when I change the color, it does affect the text itself. 

Tried to use ColorButton. But it is really harf to understant what to load. When i use the code on the screenshot I received an error
<img width="1440" alt="2015-09-13 2 38 30" src="https://cloud.githubusercontent.com/assets/1163876/9834177/2ecb493c-59b8-11e5-8e99-dac7ca65ffa7.png">
<img width="800" alt="2015-09-13 2 37 18" src="https://cloud.githubusercontent.com/assets/1163876/9834176/2ec90b36-59b8-11e5-9a09-2cca5cb40e0d.png">

**Comment by jbalsas** [comment]
Yes, `UIColor` does not affect the text, it's just not what it does ;)

To use `ColorButton`, you need to download it along with all its dependencies. Specifically, you need to download and place in the `plugins` folder the following plugins:
- [ColorButton](http://ckeditor.com/addon/colorbutton)
- [PanelButton[(http://ckeditor.com/addon/panelbutton)
- [FloatingPanel](http://ckeditor.com/addon/panelbutton)
- [Panel](http://ckeditor.com/addon/panelbutton)

Then, you need to set the `extraPlugins` property to:
```javascript
AlloyEditor.Core.ATTRS.extraPlugins.value + ',ae_buttonbridge,ae_panelmenubuttonbridge,ae_richcombobridge,ae_uibridge,colorbutton'
```

The plugin will provide two different buttons `TextColor` and `BGColor`.

**Comment by akaiworld** [comment]
Buttons appeared, but when i try to select a color the selected text is no longer selected and I get errors. 
<img width="1432" alt="2015-09-13 2 58 56" src="https://cloud.githubusercontent.com/assets/1163876/9834241/26c44fc4-59bb-11e5-8c60-d99508a06c19.png">

Also the design of the panel with buttons is awful, far not the way original alloy-editor's design is! And there is no option to select my own variant of color((

**Comment by jbalsas** [comment]
Hey @akaiworld, which version of AlloyEditor are you using? Can you provide us with an environment where we could check those out?

About the appearance and features, there's not much we can do about it since that's a third-party plugin. As mentioned in the guide about [how to use CKEditor plugins](http://alloyeditor.com/guides/how_to_use_ckeditor_plugins/), we can't convert all the UI to AlloyEditor's. What you can do is:
- Use the `moono` skin so the panel doesn't look off
- Add some custom css so it looks the way you want.
