### ISSUE TITLE
Fails to load in Electron

### ISSUE THREAD

**Issue by ColtonProvias** [liferay/alloy-editor#350]
Due to the way Electron loads JavaScript, AlloyEditor is never bound to window as it sees module first. Thus it fails to load in Electron's renderer process.

**Comment by ipeychev** [comment]
Umm, unfortunately we don't have experience with Electron and we don't know how exactly it loads the JS. Would you like to help us identifying what exactly is the problem?

**Comment by ColtonProvias** [comment]
I'm still rather new to Electron, but they heavily integrate node with it.  Thus the JavaScript is loaded as if it is in Node/io.js.

One solution I have found is to modify src/ui/react/src/adapter/main.js and swap the ordering of the conditionals on lines 195-198 so it tests for window first.  However, I'm not certain if this will break things for other users, so I'm hesitant about introducing that change as a pull request.

**Comment by ipeychev** [comment]
Go ahead and send us, we will verify it!

**Comment by iosonofabio** [comment]
I have the same problem, created a stub of electron app:

```
git clone https://github.com/iosonofabio/electroalloy
cd electroalloy
npm install
npm start
```

and you'll see in Chromium's console that AlloyEditor is not a global (for the reasons @ColtonProvias has hinted at). I thought maybe it's useful for you guys to debug...

**Comment by iosonofabio** [comment]
I had some success with this.

It's mainly about lines 195-198 of `src/ui/react/src/adapter/main.js`, i.e. lines 937 ff of `alloy-editor-all.js` and the similar section for React, lines 957 ff of `alloy-editor-all.js`.

In electron's renderer process (simlar to browserify??):
- `module` is an empty object, i.e. it is not `undefined`
- `window` exists

I was able to use Alloy Editor in electron to some degree by forcing `window.AlloyEditor = AlloyEditor` and `AlloyEditor.React = React` in those sections, **and** by loading the code into the HTML by an inline script tag:
```
<script src="<path-to>/alloy-editor-all.js"></script>
<script>
var React = AlloyEditor.React;
var AlloyEditorComponent = React.createClass({
...
React.render(React.createElement(AlloyEditorComponent, null), document.getElementById('testdiv'));
</script>
```
(see https://github.com/liferay/alloy-editor/issues/217#issuecomment-132269561 for the whole example)

The CSS does not seem to work et caetera, but more or less the functionality is there. So in this usage, one could include an `if` in those sections for cases in which both `module` and `window` are not undefined (i.e. electron).

Now, **in principle**, electron allows CommonJS (node) -style imports directly in the script tags. This is allowed in an electron `index.html`:
```
<script>
var AlloyEditor = require("<path-to>/alloy-editor-all.js");
var React = AlloyEditor.React;
...
</script>
```
This is obviously a different situation from the inlining above, and more similar to browserify, in which the dependency chain of `require`s is run down once **before** window exists. In this case, the exact opposite of the above is supposed to work, i.e. instead of forcing `window.AlloyEditor` we could force `module.exports = AlloyEditor` and `module.exports.React = React`. This has two problems though:
 1. for the case of electron, this populated the global `module`, which is probably unwanted behaviour
 2. `AlloyEditor.Lang = Lang;` fails as shown by other users, because `AlloyEditor` is not a global for itself (same for `OOP`, `Attribute`, etc.)

**Comment by ipeychev** [comment]
I just tried and it was easy to make it working:
![electron](https://cloud.githubusercontent.com/assets/78014/10358745/c4322e0e-6d91-11e5-8015-94fbbddc7a74.gif)

The only change I did was to separate the checks for module and window, i.e., instead to check for one or the another, we assume that both can be present, so we export both:
```js
if (typeof module !== 'undefined' && typeof module.exports === 'object') {
    module.exports = AlloyEditor;
}

if (typeof window !== 'undefined') {
    window.AlloyEditor = AlloyEditor;
} else if (typeof self !== 'undefined') {
    self.AlloyEditor = AlloyEditor;
} else if (typeof global !== 'undefined') {
    global.AlloyEditor = AlloyEditor;
} else {
    this.AlloyEditor = AlloyEditor;
}
```

No other changes were needed, @iosonofabio. Everything else worked OOTB. [Here](https://github.com/liferay/alloy-editor/files/9840/index.txt) is the working code.

I think similar solution was proposed by @ColtonProvias. Can you guys confirm this works for you too? If so, I will commit the code and release v0.6

Thanks,

**Comment by iosonofabio** [comment]
Thanks! That basically works but has issues:

- by inlining the alloyeditor script, like you do, `module.exports` in Electron's renderer process is still polluted by AlloyEditor:
```
<script src="../node_modules/alloyeditor/dist/alloy-editor/alloy-editor-all.js"></script>
<script>
  console.log(module.exports);
</script>
```
- requiring AlloyEditor is still not working:
```
<script>
  var AlloyEditor = require('../node_modules/alloyeditor/dist/alloy-editor/alloy-editor-all.js');
  ... (do things)
</script>
```
This is bad because it is the most common situation. Typically, people have a React app on electron and they want to plug in AlloyEditor. The app is made of a bunch of CommonJS-style modules that wil get browserified/webpacked. Most modules start with
```
var React = require('react');
```
and one would like to add to specific modules a second line:

```
var AlloyEditor = require('...alloy-editor-noreact.js');
```
But requiring AlloyEditor does not work...
```
Uncaught TypeError: Cannot set property 'dir' of undefined
```
So one could just inline AlloyEditor as a separate script tag before the browserified bundle. But AlloyEditor requires React, which is sitting in the middle of the bundle itself... the typical chicken-egg dependency problem.

**Comment by ipeychev** [comment]
Yes, this is a know issue, but I'm not sure how it can be resolved. Here are more details:
1. AlloyEditor uses under the hood CKEditr's engine, which is not an CommonJS module and cannot work in non-browser environment.
2. So far, we were making a difference between NodeJS and browser environment. If NodeJS, we were not running the CKEditor's engine, but we were exporting AlloyEditor as a module. In case of browser, we were running CKEditor's engine and the UI (this combination is actually the AlloyEditor).
3. If there were React already available on the global namespace, we were reusing it, otherwise, we would use the bundled one.

So, with browserify, there is both module.exports and window. What we should do in this situation? Should we export something to module.exports, to window, or do both? And what to do with CKEditor's engine in this situation?
I'm open to all ideas for solving this problem.

**Comment by iosonofabio** [comment]
Well, CKEditor does not depend on React. So one could inline CKEditor first, followed by a browserify bundle:
```
<script src="ckeditor.js"></script>
<script src="app.js"></script>
```
and in `app.js` we have:
```
var React = require('react');
var AlloyEditor = require('<path-to>/alloy-editor-core.js');
```
However, for this to work one should change `alloy-editor-core.js` slightly. When it checks for react, it only looks for a global variable, but if we are in a node/browserify context (i.e. if `module.exports` exists) we could fallback onto a require:
```
if (typeof module !== 'undefined' && typeof module.exports === 'object') {
    React = require('react');
} else if (typeof React === 'undefined') {
    React = AlloyEditor.React;
}
```
I tried and it almost works, except that:
- when I load CKEditor separately, no matter what I do with Alloy, I get a strange warning:
```
[CKEDITOR] editor-plugin-required
plugin: "contextmenu"
requiredBy: "tabletools"
```
- I get a missing file for language because it looks for relative paths for `lang/alloy-editor/it.js?t=F969` (my machine is curently in Italian)

**Comment by ipeychev** [comment]
The problem with the language file is more serious, let's concentrate on it for now, later on the plugin.
CKEditor's engine has a special logic for loading the language files. [Here](http://docs.cksource.com/CKEditor_3.x/Developers_Guide/Specifying_the_Editor_Path) it is. AlloyEditor uses the same approach, but with some improvements.

So:
1. If you load CKEditor separately, you will have to export a global variable, called CKEDITOR_BASEPATH. It should contain the base path, from which CKEditor will load the language files.
2. In this case you will have to do the same for AlloyEditor (the variable is called ALLOYEDITOR_BASEPATH), or to overwrite the [regex](https://github.com/liferay/alloy-editor/blob/594849ea79340f641e4d23aaeec3696d28568330/src/ui/react/src/adapter/main.js#L167), which AlloyEditor uses in order to discover the base path. Please note in CKEditor there is no way to overwrite its regex, this is the improvement I mentioned above.

One more note - when we build the dist file of AlloyEditor, we change the CKEDITOR_BASEPATH with ALLOYEDITOR_BASEPATH, so you have only one variable to overwrite (or one regex). However, when you have CKEditor loaded separately, that's not the case.

**Comment by iosonofabio** [comment]
That works, even with only the ALLOYEDITOR_BASEPATH:
```
<script>
  //CKEDITOR_BASEPATH = "../deps/ckeditor/";
  ALLOYEDITOR_BASEPATH = "../node_modules/alloyeditor/dist/alloy-editor/";
</script>
<script src="../deps/ckeditor/ckeditor.js"></script>
<script src="app.js"></script>
```
and the source of `app.js`:
```
var React = require('react');
var AlloyEditor = require('./node_modules/alloyeditor/dist/alloy-editor/alloy-editor-core.js');
var editor = AlloyEditor.editable('testdiv');
```
And I see alloyeditor's UI and I can do things (insert images, tables, etc.).

And about the plugin?

**Comment by ipeychev** [comment]
About the plugin, tell me first please, where did you get ckeditor.js? Is that one which comes from AlloyEditor, or you downloaded it from their site, for example.
Because, such plugin - "tabletools", we don't have. All our plugins have prefix "ae". We also have plugin for dealing with tables, but it is called ["ae_tabletools"](https://github.com/liferay/alloy-editor/blob/0bd5d8c9f8f427b68240f3d7f1a0c85ce6c8816a/src/plugins/tabletools.js#L654).

**Comment by iosonofabio** [comment]
Indeed I got it from their website, or via bower. I thought that was supported (otherwise what's the point of alloy-editor-no-ck-editor?), am I supposed to use the specific version shipped with alloy or to get the bare version without any plugins from the official CKE website, or do both work?

**Comment by ipeychev** [comment]
No, no, this is exactly the idea - to get the OOTB version from their site and use it.
In Liferay it is done exactly like this, because on one page both CKEditor OOTB and AlloyEditor may exist. This was a killer feature - AlloyEditor then adds just a small piece of JS on top of CKEditor's engine - the UI.
Anyway, I asked what is this CKEditor, because it shouldn't complain of missing plugins. "Tabletools" plugin requires "contextmenu", but it comes with the distribution file. Can you try to load only CKEditor on some "normal" page (not inside Electron)? You should not see any warnings.

**Comment by iosonofabio** [comment]
Results on a normal page (no electron):
- I can load CKEditor fine
```
<script src="../deps/ckeditor/ckeditor.js"></script>
```
- If I load both CKEditor and alloy-editor-no-ckeditor no complaints
```
<script src="../deps/ckeditor/ckeditor.js"></script>
<script src="../node_modules/alloyeditor/dist/alloy-editor/alloy-editor-no-ckeditor.js"></script>
```
- If I load both and call `AlloyEditor.editable`, I get the plugin error message:
```
<script src="../deps/ckeditor/ckeditor.js"></script>
<script src="../node_modules/alloyeditor/dist/alloy-editor/alloy-editor-no-ckeditor.js"></script>
<script>
  var editor = AlloyEditor.editable('testdiv');
</script>
```
maybe a version conflict? I got CKE 4.5.4 OOTB from the website.

**Comment by ipeychev** [comment]
Got it. The problem is not it the `tabletools` plugin, it is in their `contextmenu` plugin. As the name suggests, when you click with the right button, then there is a menu with different items depending on the context.

This plugin comes with basic+ version of CKEditor, which, as you may guess, we immediately remove, see the [removePlugins](http://alloyeditor.com/api/classes/Core.html#property_removePlugins) attribute. There is 'contextmenu' in its value. That's why CKEditor complains - "hey, you want me to remove contextmenu plugin, but it is required by tabletools!".
I would recommend you to modify the attribute's value and to add 'tabletools' too, like this:
```
var editor = AlloyEditor.editable('editable', {
    removePlugins: AlloyEditor.Core.ATTRS.removePlugins += ',tabletools'
});
```

In this case you will get the same functionality, but with AlloyEditor's UI.

**Comment by ipeychev** [comment]
Hey @iosonofabio,

Let's try to resolve this issue. Finally, you managed to load it to Electron successfully, didn't you? Let's try to summarize the approach you took and see if we can commit the changes you made. In general, what you did was:
1. You [changed](https://github.com/liferay/alloy-editor/blame/b5cf353a5c70cbaf86018bcac140e4b6f8fa2b54/src/ui/react/src/adapter/main.js#L195) `main.js` like this:
```js
if (typeof module !== 'undefined' && typeof module.exports === 'object') {
    React = require('react');
} else if (typeof React === 'undefined') {
    React = AlloyEditor.React;
}
```
2. You separated the loading of AlloyEditor from CKEditor's engine and removed `tabletools` plugin, like this:
```html
<script src="../deps/ckeditor/ckeditor.js"></script>
<script src="../node_modules/alloyeditor/dist/alloy-editor/alloy-editor-no-ckeditor.js"></script>
<script>
  var editor = AlloyEditor.editable('editable', {
    removePlugins: AlloyEditor.Core.ATTRS.removePlugins += ',tabletools'
  });
</script>
```

Is the above correct?

**Comment by iosonofabio** [comment]
hi,
sry I'm on a road trip until end of the month with scarce internet, but I'll have time then 100% and will make a pull request OK? I'm all for solving this issue as well...

**Comment by ipeychev** [comment]
Yeah, sure, will postpone this task to 0.6.1 then.

Thanks!

**Comment by jepezi** [comment]
Hi guys. Great project here! Notice that this issue is kinda pending so want to share how I've done it primarily based on https://github.com/liferay/alloy-editor/issues/350#issuecomment-146656434. The followings are the steps and the issues I've found along the way.
1. inline ckeditor.js in html
```
<script src="ckeditor.js"></script>
<script src="app.js"></script> // <------- bundled by webpack
```
2. require/import React and alloyeditor in `app.js`
```
var React = require('react');
var AlloyEditor = require('alloyeditor');
```
At this point, 1st error I got is `Uncaught ReferenceError: AlloyEditor is not defined`. So I modified alloy-editor-core.js a bit here.
3. Before L220, I've added this line.
```
var AlloyEditor = module.exports; // <------------ add this
var React = (function() {
...
```
4. Add React check according to @iosonofabio 
```
if (typeof module !== 'undefined' && typeof module.exports === 'object') {
    React = require('react');
} else if (typeof React === 'undefined') {
    React = AlloyEditor.React;
}
```
5. Add `removePlugins` config
```
this.editor = AlloyEditor.editable('editable', {
  removePlugins: AlloyEditor.Core.ATTRS.removePlugins += ',tabletools'
});
```
After these steps I got it working now.

**Comment by iosonofabio** [comment]
Hi @jepezi, thanks for the heads up. I am planning to draft a PR today or tomorrow. Didn't you have to change `ALLOYEDITOR_BASEPATH` like I did above?

**Comment by ipeychev** [comment]
Here is a [repository](https://github.com/ipeychev/alloyeditor-react-component) with an example of React + Webpack, might help in this case too.

Thanks,
