### ISSUE TITLE
Is there a way to work with angularjs? 

### ISSUE THREAD

**Issue by copooper** [liferay/alloy-editor#357]
Well, I try to use alloy-editor as a directive in angularjs and use ng-model to store sth on textarea, but the page cannot show it.

**Comment by copooper** [comment]
```
 let directive = {
            restrict: 'A',
            scope: {},
            link: function(scope, element, attr) {
                AlloyEditor.editable(attr.id);
            }
        };
 return directive;
```
the directive is named "editor"

and then the view is 
```
    <textarea editor id="test" ng-model="somedata">
    </textarea>
```

**Comment by ipeychev** [comment]
Hey @copooper 

For me it works, I just instantiated AlloyEditor from an Angular directive. Here is a [gist](https://gist.github.com/ipeychev/455b3b8a435d795c9667).

Here is also an animated gif:
![alloyeditor](https://cloud.githubusercontent.com/assets/78014/10483890/0d110e70-7282-11e5-9b14-4dd501ea787b.gif)

Hope that helps!

Thanks,

**Comment by copooper** [comment]
@ipeychev Thanks so much for making a demo.Yeah, it's ok when wrapped with plain text. When using ng-model, however,it doesn't work.
Luckily ,I just found a solution on stackoverflow.Here is the post:[here](https://stackoverflow.com/questions/11997246/bind-ckeditor-value-to-model-text-in-angularjs-and-rails)
Thanks again.

**Comment by ipeychev** [comment]
Great!

**Comment by thiagogarbazza** [comment]
Directive for _Angular_ created. 

```html
<alloy-editor id="myEditor" name="myEditor" ng-model="model.content"></alloy-editor>
```

See [this repository](https://github.com/thiagogarbazza/angular-alloyeditor)  for more information.

**Comment by riteshjagga** [comment]
I checked that `alloy-editor` directive doesn't work when nested inside `ng-show` directive.

**Comment by riteshjagga** [comment]
I eventually found that problem with `ng-show` can be solved using this code.

    <div ng-show="(selectedObjectType === 'front-page')">
      <alloy-editor id="myEditor" name="myEditor" ng-model="vm.content"
                        readonly="!(selectedObjectType === 'front-page')"></alloy-editor>
        </div>

It uses `readonly` attribute with the value as *negation* of `ng-show` expression.

Here are references where this issue is discussed:
 1. (http://ckeditor.com/forums/Support/inline-editor-div-contenteditable-when-loaded-hidden-doesnt-work.)[http://ckeditor.com/forums/Support/inline-editor-div-contenteditable-when-loaded-hidden-doesnt-work.]
 2. (http://stackoverflow.com/questions/21202684/ckeditor-inline-editing-on-jquery-ui)[http://stackoverflow.com/questions/21202684/ckeditor-inline-editing-on-jquery-ui]
