### ISSUE TITLE
React 0.14

### ISSUE THREAD

**Issue by dantman** [liferay/alloy-editor#365]
`react@^0.14` has been released. It would be nice to consider switching to it in the next major release. Right now when alloy-editor is used in a page that uses React 0.14, AlloyEditor makes react emit deprecation notices for things that'll break in the following release.

**Comment by ipeychev** [comment]
Yeah, thanks for the heads up, we will migrate it

**Comment by jbalsas** [comment]
Hey @dantman, that's definitely on our todo list. We'll try to get to it asap.

However, I think both @ipeychev and myself are quite swamped right now, so we will gladly review any contribution regarding this if it comes before we can tackle it :)

@ipeychev, based on the underlying changes in React, should we schedule the update for a 0.7 release instead of 0.6.1?

**Comment by ipeychev** [comment]
Yeah, depending on how much changes we have to do, it could be 0.7 too

**Comment by nickbouton** [comment]
+1 for React 0.14 integration.

**Comment by jbalsas** [comment]
On its way! https://github.com/liferay/alloy-editor/pull/370 :wink:

**Comment by nickbouton** [comment]
@jbalsas thank you!
