### ISSUE TITLE
Bug: calling editor.destroy() throws javascript error

### ISSUE THREAD

**Issue by brunobasto** [liferay/alloy-editor#375]
Hey guys,

Found a small issue. To reproduce, try this: https://github.com/brunobasto/alloy-editor/commit/9b71aff126d1f755ae90b107f8b8161c165927d8

Thanks,

**Comment by ipeychev** [comment]
Hey @brunobasto,

Thanks for the report! The exception is not in our code, but in CKEditor's engine itself. It seems they don't like when you create an instance of the editor and then immediately destroy it. 
This is not a critical bug, since normally the editor won't be destroyed immediately after its creation.
Keeping that in mind, we will have to upgrade to newer version of CKEditor (if any), or to report it and wait for a a fix.

Thanks,

**Comment by brunobasto** [comment]
Got it! Thanks, @ipeychev

**Comment by ipeychev** [comment]
Hey @brunobasto,

It seems in CKEditor v4.4.5 this is fixed, they now throw a warning (http://docs.ckeditor.com/#!/guide/dev_errors-section-editor-incorrect-destroy). @jbalsas could upgrade to this version and this upgrade will fix #381.

Thanks,

**Comment by brunobasto** [comment]
Thanks, guys!
