### ISSUE TITLE
ERR_INVALID_URL when moving an image in the content

### ISSUE THREAD

**Issue by projer** [liferay/alloy-editor#381]
Hi!

First I wanted to congratulate you for your RTE, very nice job!

I was testing it, and I found that on Chrome and Opera when you paste an image inside and move it, after the second time, an ERR_INVALID_URL appears in the console, which results in inserting strange characters (â€‹), and even from time to time it duplicates the image.

Looks like it works perfectly on Firefox.

Thanks!
![2015-11-20_15h31_41](https://cloud.githubusercontent.com/assets/3242718/11302137/ddb6354c-8f9b-11e5-8745-06c680c4245c.png)

**Comment by ipeychev** [comment]
Hey @projer,

Thanks for the reporting and for the nice words!

This issue seems to be not in our code but in the CKditor's engine, which we use. When that happens, here is how we proceed:
- If the bug is critical, we report it and meanwhile we try to fix it by ourselves or at least to narrow it down.
- If not critical, we report it and upgrade to a new version when they fix it.

Since the normal behavior is the image to be immediately uploaded and with a "real" URL the bug cannot be reproduced, I will consider this bug as not critical.

Thanks,

**Comment by ipeychev** [comment]
Chema, could you please go ahead and update CKEditor to their latest version (currently 4.4.5)? It seems this issue is fixed there and the upgrade will fix #375 too (they now throw a warning - http://docs.ckeditor.com/#!/guide/dev_errors-section-editor-incorrect-destroy)

@jbalsas 
Thanks,

**Comment by jbalsas** [comment]
Hey @ipeychev,

I've updated the version [here](https://github.com/liferay/alloy-editor/pull/382)

I tried it out and indeed the error stops showing, but because the behaviour with CKEditor 4.5.5 seems to be that images with base64 content as urls can not be moved around.
