### ISSUE TITLE
Support for vertical orientation of the overlay toolbar

### ISSUE THREAD

**Issue by srad** [liferay/alloy-editor#383]
I haven't seen it in the docs, but do you support a configuration to orient der elements in the overlay-toolbar vertically?

**Comment by jbalsas** [comment]
Hey @srad, 

I don't think we're supporting a vertical toolbar per se, but it shouldn't be that hard to implement. Since we're using flexbox, setting `flex-direction: column;` for the `ae-container` class would make the elements show in vertical. However, you'll probably still need to do some extra adjustments to things like the toolbar position.

Could you explain your use case and what you're trying to achieve with a little bit more detail, please?

**Comment by srad** [comment]
Sure, it's just a requirement. The menu is supposed to look like a more traditional context-menu and the number of buttons/element might be a little longer, so it's more convenient and familiar - in our context - to use it vertically.

**Comment by wincent** [comment]
Doing some "spring cleaning" by closing issues that were opened in 2015 — much has changed since then and there have been many releases, so there is a risk that these older issues have grown very stale and are very unlikely to be acted upon. Please feel free to commend and we can look at re-opening on a case-by-case basis.
