### ISSUE TITLE
Text alignment + headings issue

### ISSUE THREAD

**Issue by nickbouton** [liferay/alloy-editor#386]
Right now, if you use `text-align: center` (via the `paragraphCenter` toolbar button) in conjunction with a heading tag from the toolbar styles dropdown (e.g. `H1`, `H2`, ... `H6`), the centering style is stripped when the `<p>` tag surrounding the text is replaced with a heading element. Not sure if there is a configuration parameter I'm missing in the toolbar setup, or if this is unintended functionality (read: a bug.)

The problem appears to be bidirectional, i.e. converting from centered "normal" text to `H1` strips centering, and attempting to center a heading tag removes the heading markup.

Someone else mentioned this problem in the comments in the [AlloyEditor docs for paragraphRight](http://alloyeditor.com/features/paragraphalignright/) and @ipeychev suggested creating an issue here, so here you go.

**Comment by jbalsas** [comment]
Hey @nickbouton, thanks for taking the time to report this!

I've been looking into it, and unfortunately this is actually the expected behaviour for our `paragrah-` buttons right now. They will change the element to `<p>`, thus removing any other styling.

I checked, and CKEditor's [justify plugin](http://ckeditor.com/addons/search/plugins/justify) does so much more than ours.

If you need this functionality, you could download the plugin and add it to the editor configuration along with our `ae_uibridge` and `ae_buttobridge` plugins. Then, you could place the following buttons in your toolbar that will keep the alignment no matter the element: `JustifyLeft`, `JustifyCenter`, `JustifyRight`.

@ipeychev I agree that this looks like a bug from the outside... do you think we should change our implementation to match or use that of CKEditor's justify plugin?

**Comment by ipeychev** [comment]
Yeah, Chema, I think so!

**Comment by jbalsas** [comment]
Ok, not sure when I'll have time to work on this, but I'll keep it on top of my list :)

**Comment by jbalsas** [comment]
I'll try to work on this today, which should also fix #206

**Comment by duracell80** [comment]
"If you need this functionality, you could download the plugin"
Not acceptable at all. This is basic functionality that should be working and is missing from Liferay DXP.
