### ISSUE TITLE
"This seems to be a pre-built javascript file" webpack error.

### ISSUE THREAD

**Issue by fractall** [liferay/alloy-editor#391]
Hello friends,

Whenever I bundle with webpack i'm getting this error:

    WARNING in ./~/alloyeditor/dist/alloy-editor/alloy-editor-all-min.js
    Critical dependencies:
    744:425-432 This seems to be a pre-built javascript file. Though this is possible, it's not recommended.         Try to require the original source to get better results.
     @ ./~/alloyeditor/dist/alloy-editor/alloy-editor-all-min.js 744:425-432

How can I fix this?

**Comment by ipeychev** [comment]
Hello!

This is Webpack's message and I think it complains because it has to minify a file, which is already minified ("alloy-editor-all-min.js"). You may Google a bit, there are similar issues and they are all related to this.

As an advice - do not include AlloyUI to your applications's files. Include it to the page as a separate script. You will leverage browser's caching and better performance results as whole.

Thanks,

**Comment by ipeychev** [comment]
Hope that helped, please reopen if not.
