### ISSUE TITLE
Cmd-L to open Link Dialog

### ISSUE THREAD

**Issue by kushal** [liferay/alloy-editor#417]
It looks like the default CKEditor has a shortcut for adding a link, but it appears to not be in Alloy, and I can't quite figure out how to add it. Any tips or insights? Thanks!

**Comment by ipeychev** [comment]
Hey @kushal,

We currently don't support this. In general, AlloyEditor is able to work with the keyboard (and it is also screen reader friendly) - by pressing `Alt+F10` the toolbar will be focused and then you will be able to navigate using they arrows. Going back and forth to the next Toolbar is done using `Tab`.
However, directly invoking specific commands is not supported and I think this will a good feature.

**Comment by jbalsas** [comment]
Hey @kushal, as @ipeychev pointed out, some keystrokes aren't currently available in `AlloyEditor` because they're added by some `CKEditor` plugins we're not using. I'm working on a fix for this, that will allow creating keystrokes for the buttons. 

Keep in mind, though, that `AlloyEditor` works in a different way, so the keystrokes will only be available as long as the button holding the required functionality is available in a toolbar. This means you won't be able to create a link just by pressing `Cmd + L` if you haven't selected any text. For that, however, we enable `ae_autolink` by default which creates links automatically as you type.

**Comment by kushal** [comment]
This works great, thanks!

Out of curiosity, is there even a hacky way to make cmd-L work when no text
is selected?

**Comment by jbalsas** [comment]
Hey @kushal, as @ipeychev would say, _"we are developers, we can do anything"_ :wink: 

I think you could:
- Have `cmd-L` trigger a command that would [create a CKEditor bookmark](http://docs.ckeditor.com/#!/api/CKEDITOR.dom.range-method-createBookmark)
- Create an additional selection with the `linkEdit` button that would test true for the created bookmarks

If everything plays out and a `selectionChange` event is triggered when creating the bookmark, that should prompt the special toolbar with the edit button. You'd need to take care of registering/unregistering the commands so the don't clash, but that's a way I can see it working.

@ipeychev, what do you think? Would you like to have this behaviour out of the box?

**Comment by ipeychev** [comment]
I vote with +1, definitely!

**Comment by jbalsas** [comment]
Will work on that, then :wink:

**Comment by ipeychev** [comment]
That proves you are a real developer :)

**Comment by jbalsas** [comment]
Hey @kushal, we just implemented this in #422. Should be in for the next release :wink:

**Comment by kushal** [comment]
Very cool!
