### ISSUE TITLE
Add functionality to drag/drop selected text content around.

### ISSUE THREAD

**Issue by blzaugg** [liferay/alloy-editor#42]
I looks like you can select and drag text around. But when you drop it, nothing happens. This appears to be a native browser feature but has no effect. Maybe because we don't handle it? Not sure.

**Comment by wincent** [comment]
Testing this now it seems that dragging and dropping works (both in current 2.x-develop branch and the version currently in the portal master branch), so I think this might have been fixed by an update at some point over the years. So I'll close this for now; if this is mistaken (for example, if it still repos on Windows) let's re-open this.

**Comment by blzaugg** [comment]
Yes, it's been solved.
