### ISSUE TITLE
Camera button throws an exception in Chrome after capturing the image

### ISSUE THREAD

**Issue by jbalsas** [liferay/alloy-editor#420]
Currently, the camera button image throws an exception after capturing the image. This is caused because the implementation seems to have switched to https://developer.mozilla.org/en-US/docs/Web/API/MediaStream which does not have a `stop` method anymore.

We should investigate the different ways to do it now, and the proper way to ensure it works across all the supported browsers.

**Comment by antoniopol06** [comment]
I can´t reproduce this error.

**Comment by ipeychev** [comment]
Hey @antoniopol06,

The issue is on Chrome, at least on my Mac. Chrome reports the following issue:
`alloy-editor-all-min.js:780 getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.`
In the issue description it is written: `throws an exception **after** capturing the image.`. It is actually not after, the browser refuses to create media stream at all on insecure domains.

**Comment by jbalsas** [comment]
I think I saw this on Firefox after seeing that Chrome no longer worked... I tried and I can't reproduce it either, so I'll reopen if I remember what was going on :(

**Comment by jbalsas** [comment]
Oh, I actually realized that the title says Chrome... wonder how did I manage to do that :joy:

**Comment by ipeychev** [comment]
:)
Yeah, on Chrome. On Firefox it works like charm - no warnings and photo is there.
Here is a screencast on the live page on my machine, opened with Chrome 47.0.2526.106 (64-bit):
![bug](https://cloud.githubusercontent.com/assets/78014/12307779/c4a11c0e-ba41-11e5-93cb-d7269dc5506c.gif)

**Comment by jbalsas** [comment]
Ok, after a good night's sleep, I remember how to reproduce this :relaxed: 

We just need to follow one of the two ways of [Testing Powerful Features](https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins) in Chrome explained in the article.

Basically, run the demo on your local machine on localhost and you'll see the error.

After fixing #421, I'm guessing we won't be able to test it on chrome at all, which makes me think the fix we applied might not be the ideal one...

@antoniopol06, @ipeychev, what do you think?

**Comment by ipeychev** [comment]
Hey Chema,
Yeah, since it is disabled even on localhost, it won't be easy to be tested, true. We can always update the code to accept `localhost`, which as it seems Chrome likes. In any case, I'm not so happy that they disabled these features on non-secure origins, but I don't see what else we can do, except to disable the button on http.
Apart from that, we definitely should update alloyeditor.com to go via https by default. Why don't you contact the domain admin and request such a change?

Thanks,
