### ISSUE TITLE
Max value for table`s rows and cols inputs.

### ISSUE THREAD

**Issue by sergiy-evision** [liferay/alloy-editor#432]
Currently if you put 1000 as number of rows (cols) browser will die..
May be some config for max allowed (supported) rows and columns will be beneficial?

**Comment by ipeychev** [comment]
I wouldn't say we can do something here.
Browsers are not equal in performance and what is slow in one browser it might be fast in another one.
Second, what is slow in a particular browser today, might be fast tomorrow.
And third, from our point of view we support arbitrary number of columns and rows. We can't limit our feature because of third party issues.

**Comment by nickbouton** [comment]
@ipeychev I have a similar question but at the opposite end of the spectrum (i.e. not a performance-based limit or anything browser-related.)

We're developing an app that has a Trello-like board/card editing feature. We're using Alloy for rich text editing right now, but we have some custom templates within our editable widgets that require locking the content down to 1-, 2-, or 3-column widths.

Is it possible to limit the number of columns allowed to an arbitrary (low) number in an Alloy table, currently?

**Comment by ipeychev** [comment]
Hello,

Currently not. It will be very easy to do it - you may add two more configs to the button, `maxcolumns` and `maxrows` for example and then pass the values via `buttonCfg` property of the editor. I encourage you to do it and send us pull request.
Otherwise, you can always extend ButtonTableEdit class and override _createTable function.

Thanks,
