### ISSUE TITLE
Changing target when creating link steal focus

### ISSUE THREAD

**Issue by sergiy-evision** [liferay/alloy-editor#434]
Got this strange behavior when adding a link.
1. type and select some text
2. select link from toolbar
3. change target from default to any other
4. try to enter a link
after each key press focus will be stolen by target dropdown.
reproducible in any browser on live demo page http://alloyeditor.com/demo/

**Comment by sergiy-evision** [comment]
and one more question. is it possible to disable target seletor all together and set defaul target to "_blank" :question: 
Thanks

**Comment by ipeychev** [comment]
@jbalsas

**Comment by jbalsas** [comment]
Hey @sergiy-evision, I'll look into the focus issue.

About disabling the target selector, it is possible to pass a `showTargetSelector` property to the `linkEdit` configuration so it doesn't show the selector. The value is set to `true` by default since it's the use case we support out of the box.

**Comment by sergiy-evision** [comment]
Thanks, @jbalsas for suggestion!
However, i wanted to set default target to _blank instead of empty, but had no luck with this. Would be great if you could point me to right direction.

Regards,

**Comment by jbalsas** [comment]
Hey @sergiy-evision, there's currently no way to configure the default target value... It should be easy enough to add an additional property `defaultLinkTargetValue` to the `button-link-edit` component so the default target state is set to it instead of just the empty string.

I'll try to work on that, but I'm not sure when will I have the time for it, so if you could send a PR with it, it'd be awesome!
