### ISSUE TITLE
Does alloyEditor support sharedSpaces?

### ISSUE THREAD

**Issue by ebarra** [liferay/alloy-editor#435]
We want to use alloy-editor in a project and we would like to know if it supports sharedSpaces to have an external shared toolbar for different editable zones.

Thank you

**Comment by ipeychev** [comment]
Hello,
You mean to support something like CKEditor's Shared Spaces plugin, i.e. multiple editing areas and one toolbar which handles all the areas, don't you? This one:
http://ckeditor.com/addon/sharedspace

The idea of AlloyEditor is to have context toolbars, which appear next to the selection, wherever it is. We don't support officially the "traditional" approach with one fixed toolbar (despite it is doable in a hacky way).
This also means we currently don't support one shared toolbar OOTB - you will have to create an instance per editing area. Creating instance is cheap, there are no iframes, React handles the events, so...
If Shared Spaces support is a must for your project, could you share what are its benefits? If they are significant, we can do it too.

Thanks,

**Comment by ebarra** [comment]
The reasons are that we have an open source presentations software where we
use ckeditor 3 with that functionality. The user has several boxes editable
to create his/her presentation. See and example here:
https://youtu.be/Ru2yiJl9uQY?t=1m22s

We are rewriting it with react and would like to use ckeditor 4 but we see
that you are a react project extending ckeditor and would like to give your
software a try instead of ckeditor.

Thank you very much
Enrique

**Comment by ipeychev** [comment]
I see. Yeah, with CKEditor what you did was a good choice. However, with AlloyEditor this won't be needed. There is no need to have one toolbar on top and the user to be distracted and bounce his eyes from the editing area to the toolbar on top and back. You can do it much better - by letting your user focused on the content he creates. With AlloyEditor, the toolbar will appear where it should be - next to the selection, on whatever editing area and armed with the needed buttons only. You will be able to simplify your UX and move it one level up. You almost have it, [here](https://youtu.be/Ru2yiJl9uQY?t=86) I see beautiful context icons, but then an ugly toolbar on top and I know why you did it in this way - because that was everything CKEditor provided. Now you have the chance to move one step further and make everything context dependent. This will be much better for your clients.
