### ISSUE TITLE
Toolbar add does not appear when editable content is empty and you click it.

### ISSUE THREAD

**Issue by antoniopol06** [liferay/alloy-editor#450]
If you use the demo and remove all content from editable content and after that, you click it, toolbar add will not appear.

**Comment by ipeychev** [comment]
@antoniopol06, do you mean the demo page on [alloyeditor.com](http://alloyeditor.com/demo/), or our local demo page? Also, on which browser is that happening?
Because, on our local demo page I can't reproduce this. It shows correctly once you remove all content and click inside.
On the demo page on alloyeditor.com however there are indeed some issue, basically, I can't even type inside, I delete all content. However, I'm not sure how [this change](https://github.com/antoniopol06/alloy-editor/commit/a668a3ee2abf30fe897d28b4988cbe15a5ff1bef#diff-d08a0fe0e1642a760d7f941c19ff85b4R113) fixes it. Why adding on one more event plus changing the precedence of the listeners fix the issue? Again - I can'y reproduce this on Chrome and on [this](https://github.com/liferay/alloy-editor/blob/be140ea6a08dcdbb23ef84f2b7f7a6e5ee982046/src/ui/react/demo/index.html) demo page.

**Comment by antoniopol06** [comment]
@ipeychev This happens on Chrome, If you focus on different content editables, you lose sometimes the focus and the toolbar add does not appear, This happens in this demo and the alloyeditor demo too.

![focus](https://cloud.githubusercontent.com/assets/3017821/12638076/8d67f7c6-c59a-11e5-92c0-61d7bae4cfaf.gif)
