### ISSUE TITLE
Evaluate joining the Editor Recommendations Project 

### ISSUE THREAD

**Issue by jbalsas** [liferay/alloy-editor#460]
CKEditor is launching [The Editor Recommendations Project](https://medium.com/content-uneditable/the-editor-recommendations-project-6aacd0b1c4f4).

I'm just opening this here to evaluate and check if (and how) we could or should try to contribute there.

**Comment by ipeychev** [comment]
Hey Chema,

I know about this initiative and I remember asking myself the same question like those you posted. I'm not sure what value we could provide to them. From what I see [here](http://ckeditor.github.io/editor-recommendations/) they are trying to provide two things:
1. Some kind of standard markup among the browsers as result of commands
2. General recommendations about what a blog post should consist from, also "Private Message", etc.

IMHO, # 1 kinda makes sense, # 2 does not.

Since we operate on a higher level, these recommendations are not so interesting for us. What I would love to have is more high level features, directly coming from the browsers. On top of my head -embedding content, mixing editable with non-editable parts of the editable area, syntax highlighting... in other words these things which are currently provided by the editors to become standardized and implemented by the browsers. However, I'm not very optimistic that this will happen. For ~15 years browser vendors couldn't achieve consistence about the inserted markup as result of some command, neither were able to fix brutal [bugs](https://bugs.webkit.org/show_bug.cgi?id=15256) in their implementations, which stay there for years, so...

How would you like to contribute to this project?

Thanks,

**Comment by jbalsas** [comment]
Hey Iliyan, 

You're most likely right... I just saw the initiative (and was about to hop on a plane) and wanted to run this by you, just to analyze if it made sense to do something about it.

For #1, you're right that for now we work on a higher level, so probably this is a little bit out of scope.

Looking carefully into it, I think for #2, it might be valuable for Liferay to try to play a part in the `Use Cases` definition, maybe gearing the default experience towards what we're achieving with AlloyEditor.

In any case, I think we have our hands full for now :joy: 

Closing for now... thanks for taking the time to look into this!!

**Comment by ipeychev** [comment]
About 2), in not sure how this can be standardized or to create recommendations about it and moreover, how is it related to the editors at all.
This is an UX topic, and second, if you remember, a few years ago the "recommendations" for a blog would be different - a bloated editor with fixed toolbar on the top and a lot of functionality which no one uses. Now the "recommendations" are different. Tomorrow they will be different too and i don't really understand what is the purpose of this standardization, except if they want to document what is "modern" today" :)

Thanks,

**Comment by jbalsas** [comment]
Yeah, I agree, I was just thinking that maybe Juan, Ivan or someone else in PM or UX could want to give their "recommendations" and, as you say, "shape what is modern today" :joy:
