### ISSUE TITLE
Toolbaradd does not appear when content editable has width that its value is 100%

### ISSUE THREAD

**Issue by antoniopol06** [liferay/alloy-editor#476]
Now, toolbaradd appears next to content editable (left side). In responsive design, usually, this kind of divs has width that its value is 100% (or almost 100%) on mobile devices and the toolbaradd does not appear totally. How can we handle it? Where should toolbaradd appear?

Thanks!

**Comment by ipeychev** [comment]
I would say either on left, or on right, where there is a space for it. When the UI is designed, it should be designed with this requirement in mind. Responsive design is not different than any other, the toolbar by default appears on the left in order to be as close as possible to the carret, but without covering the content.

**Comment by wincent** [comment]
By way of "spring cleaning", I'm closing issues tagged with "question" that haven't had any activity in > 12 months. There have been quite a few releases since then and much has changed, and these "stale" issues are extremely unlikely to be acted on. Please feel free to comment and we can re-open on a case-by-case basis.
