### ISSUE TITLE
example use with React 0.14

### ISSUE THREAD

**Issue by ali1k** [liferay/alloy-editor#477]
Hi, thanks for the nice work. the demo that you have on your website, seems to work on the old version of React. Do you have any example/tutorial based on React 0.14 where Mixins are not supported anymore. I also couldn't find your react component on npmJS repository. Is there any plan to put it on npmjs.com ?

**Comment by ipeychev** [comment]
Hello,

There is some misunderstanding, React 0.14 supports mixins. In fact, AlloyEditor 1.0 uses React 0.14.2. Also, which demo on our site you are mentioning, that works with old version of React?
Mixins are not supported when the code is written in ES2015. This however is important only if you want to develop AlloyEditor or to create your own buttons and you want to use ES2015. To replace the mixins with something else is in our plans. However, it is hard to take a decision with what and how? There are a few possible ways. We may go with a solution, based on [this](https://gist.github.com/sebmarkbage/fac0830dbb13ccbff596) gist. We also would appreciate any ideas, do you have some?

We haven't published the [React component](https://github.com/ipeychev/alloyeditor-react-component/blob/master/src/alloyeditor.js) (I hope you mean this one) to NPM, just because it is an example and basically it just creates/destroys an instance of AlloyEditor. In production mode, you would want more - for example to subscribe/unsubscribe to some events, to get data, etc. but this is an application logic and it cannot be part of an example, can it? Apart from that, shall it be written in ES2015 or not? That's why it is an example, a base on which you can write a real component which will fit your scenario.

Hope that helps!

Thanks,

**Comment by ali1k** [comment]
thanks a lot for your kind response. Sorry for the confusion. I meant exactly using your editor in ES2015 where Mixins are not supported. People usually use solutions like [1] to adapt Mixins in ES6 syntax.
I was referring to your example extension in [2] which Mixins are used.
We are reviewing existing WYSIWYG editors which would integrate well with our isomorphic flux architecture. In our use case, accessibility features are very important. In addition to that, we would need to make a lot of customized extensions for the editor, therefore, flexibility is also very crucial for us.
AlloyEditor sounds pretty neat. The only issue we are facing now is that our code is in ES2015 and don't know how difficult it would be to adapt it in there.

[1] https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750#.rdnm76pi6
[2] http://alloyeditor.com/demo/

**Comment by ipeychev** [comment]
Hello,

Well, for now you will have to use Ract.createClass when you create extension and want to use existing AlloyEditor's mixins. Otherwise you should be able to write classes and extend `React.Component` without issues.
We are definitely going to work on replacing the mixins with something else. Dan Abramov's approach is questionable, see the [comment](https://medium.com/@danikenan/you-lose-so-much-with-your-solution-especially-with-es6-bcf4fdad40be#.nnneaookm) below the article.
Maybe we will start checking this [this](http://justinfagnani.com/2015/12/21/real-mixins-with-javascript-classes/) approach first. I opened an issue [here](https://github.com/liferay/alloy-editor/issues/479).

Thanks,

**Comment by ali1k** [comment]
thanks for the response. I will be looking forward to your solution for replacing Mixins...

**Comment by ipeychev** [comment]
Thanks!

**Comment by ipeychev** [comment]
Here is a branch where it will happen: https://github.com/liferay/alloy-editor/tree/mixins

**Comment by onyii5119** [comment]
I installed via npm (version 2.0.4): 
npm i alloyeditor

In my React (version 16.8.6) component:
import AlloyEditor from 'alloyeditor';

var alloyEditor = AlloyEditor.editable('MyEditorId');

TypeError: Cannot read property 'editable' of undefined. The error points to the line above.

Please how can I resolve the error?

**Comment by wincent** [comment]
Would you mind creating a separate issue for this question @onyii5119?
