### ISSUE TITLE
Select builds when install with NPM

### ISSUE THREAD

**Issue by devmarco** [liferay/alloy-editor#487]
Would be very good if we coud select builds when install with NPM.

Something like:

```
import alloyeditor from 'alloyeditor/no-react'
```

The full project is too big, since I already have Jquery and React on my project.
Is it possible? Today we have a way to select different builds when install alloy using NPM?

**Comment by ipeychev** [comment]
We do not support this OOTB, so I will convert this question to a feature request.

Thanks,

**Comment by wincent** [comment]
This issue is quite old now but I believe it can be closed. Please let me know if I'm mistaken.

These are the build variants that are included in the "dist" folder with the package that we ship via NPM:

```
alloy-editor-all-min.js
alloy-editor-all.js
alloy-editor-core-min.js
alloy-editor-core.js
alloy-editor-no-ckeditor-min.js
alloy-editor-no-ckeditor.js
alloy-editor-no-react-min.js
alloy-editor-no-react.js
```

The default export you get if you import is `dist/alloy-editor/alloy-editor-no-react.js`, but I believe you should be able to require any of the variants with `import 'alloyeditor/dist/alloy-editor/alloy-editor-core'` and so on.

**Comment by blzaugg** [comment]
@wincent, is/will this be documented?

**Comment by wincent** [comment]
[This](https://alloyeditor.com/docs/use/use.html) is where I would expect it to be documented, but it currently isn't. @edalgrin-work just ported the website to the Gatsby boilerplate, but no content updates yet; @mwilliams2014 is likely to work on content updates over the next week or two, so we could add this to the list of items to attend to. I've created https://github.com/liferay/alloy-editor/issues/1161 to start tracking all the things that we'd like to make sure are covered (currently only has one item on it; we actually have to flesh it out!).
