### ISSUE TITLE
Cannot Remove Embed Link from Editor

### ISSUE THREAD

**Issue by btknorr** [liferay/alloy-editor#517]
We are using the most basic form of AlloyEditor, no plugins or anything.  Just using AlloyEditor.editable('myContentEditable'); like stated in the guide.

Everything works great until you add an embed link.  Once it's there, it cannot be removed.  How do you remove an embed link?  If you select it, the embed link field pops up, and if you click the X, and then the checkmark, it still remains.  If you select it and then hit the backspace key, the browser goes back in it's history to the previous web page.  Very frustrating...please advise.

Thanks,

Brian

**Comment by btknorr** [comment]
Try it yourself using the AlloyEditor demo, just add an embed link and then try to remove it :)

http://alloyeditor.com/demo

**Comment by jbalsas** [comment]
Hey @btknorr, I just verified the issue. I think it only happens if the embed content has an iframe. We have some code that forces the widget selection so it triggers a `selectionChange` event which seems to be causing the inner iframe to be focused making it impossible to remove.

If you're building AlloyEditor yourself, you may try commenting [this line](https://github.com/liferay/alloy-editor/blob/master/src/plugins/embed.js#L104) and rebuilding the editor.

We'll work on this next week to come up with a complete solution to this.

Thanks for letting us know about it, and sorry for the inconvenience!

**Comment by jbalsas** [comment]
On a related note, this fix in upstream CKEditor might be relevant: http://dev.ckeditor.com/ticket/14538

**Comment by ipeychev** [comment]
Hey Chema,

I was going to release this weekend ver. 1.5.1 which includes the fix for https://github.com/liferay/alloy-editor/issues/515 (great job from @antoniopol06 and you), but in this case let's postpone it for one week and include the fix for this issue too, okay?

Thanks,

**Comment by jbalsas** [comment]
Hey Iliyan, yeah, I agree. We'll work on this next week. 

BTW, I think we should be planning `1.2.1`, we're currently at `1.2.0` 😅

**Comment by ipeychev** [comment]
Yeah, correct, `1.2.1` of course - too many projects and I started to get confused which one is on which version :D 
Btw, talking about versioning, do you know [Semantic release](https://github.com/semantic-release/semantic-release)/[Commitizen](https://www.npmjs.com/package/commitizen)? They help people to have better change logs and better versioning. Maybe it will be good idea to think for adopting them.

Thanks,

**Comment by jbalsas** [comment]
I just sent a fix proposal for this (#517), including:
- Allows for easy removal of the widgets using the keyboard
- Adds a remove button to the embed toolbar like the one when editing a link

**Comment by jbalsas** [comment]
@ipeychev, regarding the versioning, it does definitely sound interesting... let me take a look once I find some time for it, and I think this could be a nice playground to experiment with those ideas.

Thanks!
