### ISSUE TITLE
Any way to specify where to get language resources from?

### ISSUE THREAD

**Issue by jimmiebtlr** [liferay/alloy-editor#519]
Looking through I'm not seeing any way to specify where a language resource get's pulled from (url wise).  Ex: en.js

**Comment by jimmiebtlr** [comment]
Also, looks like it's randomly requesting styles and config from a relative path?

**Comment by ipeychev** [comment]
Hey @jimmiebtlr,

There are some resources which are requested on the fly from CKEditor's engine and the language files are requested by AlloyEditor. The resource files, loaded by CKEditor's engine are needed, because you may decide to use some of CKEditor's plugins inside AlloyEditor. The language file is loaded on the fly to not include all the supported language files in the bundle and increase the size of AlloyEditor with ~60KB.

In general, the rules from where to load these resources are:

1. The path to these files will be guessed from the URL from which the editor is loaded. If the editor is loaded using a `script` element as shown [here](http://alloyeditor.com/guides/) this should work OOTB.
2. If the script file is concatenated with other files (which is not recommended), or it was renamed, or the bundle is constructed by some loader like Webpack, then the path to the resource files should be specified manually. There are two variables which have to be specified:
```javascript
// this variable is needed by AlloyEditor to load the language file
window.ALLOYEDITOR_BASEPATH = 'the path to the resource files here';
// this variable is needed by CKEditor's engine, because
// you may want to use CKEditor's plugins inside AlloyEditor
window.CKEDITOR_BASEPATH = 'the path to the resource files here';

// In most of the cases these two variables will have same value
```
If these variables are specified, they will take precedence and AlloyEditor will not try to determine the path automatically.

Please look at [this](https://github.com/ipeychev/alloyeditor-react-component/blob/master/src/index.html#L17) example.


Thanks,
