### ISSUE TITLE
Editable Dropdown Menu

### ISSUE THREAD

**Issue by qasid** [liferay/alloy-editor#536]
User cannot edit value of drop down menu for quick selection or give custom value. e.g Font size and styles drop down.

**Comment by Tlapi** [comment]
+1

**Comment by wincent** [comment]
Doing some "spring cleaning" by closing issues that were opened in 2016 — much has changed since then and there have been many releases, so there is a risk that these older issues have grown very stale and are very unlikely to be acted upon. Please feel free to commend and we can look at re-opening on a case-by-case basis.
