### ISSUE TITLE
Selection menu and the add button does not appear in a widget

### ISSUE THREAD

**Issue by ingesy** [liferay/alloy-editor#554]
If the first click in an editor is within a ckeditor-widget, the alloyeditor menu does not appear until you click outside of the widget, then inside again.

**Comment by ipeychev** [comment]
Hello,

Would it be possible to create a simple HTML to be easier to reproduce?

Thanks,

**Comment by ingesy** [comment]
Sure, i attached a small repro of this issue.
[alloyeditor-case.zip](https://github.com/liferay/alloy-editor/files/329662/alloyeditor-case.zip)

**Comment by jbalsas** [comment]
Thanks for the test case, @ingesy!

Looks like an issue with the editor not gaining focus on the widget click... will investigate.

Thanks for reporting this!

**Comment by ingesy** [comment]
No problem. I've tried to work around this issue, but haven't found a good way to do it. 

Did you find anything interesting when looking into this?

**Comment by wincent** [comment]
By way of "spring cleaning", I'm closing issues tagged with "question" that haven't had any activity in > 12 months. There have been quite a few releases since then and much has changed, and these "stale" issues are extremely unlikely to be acted on. Please feel free to comment and we can re-open on a case-by-case basis.
