### ISSUE TITLE
Can i change show the plus (+) toolbar button on hover instead of on clicking in the editor?

### ISSUE THREAD

**Issue by bilalakmal** [liferay/alloy-editor#576]
Hi there,
I am loving the editor, but now I want to change a little UI. I want to show plus(+) button on hover instead of clicking in editor. Is it possible? Can you help me on this ? I am searching but I think no one ever asked this question before.

**Comment by ipeychev** [comment]
Hello,

This won't be trivial, because the toolbar currently follows the common approach - every time the user interacts with the editor (clicks with the mouse or presses a key), the toolbars hide/show/adjust themselves.
This means you will have to fork the editor and change the code since there is no such option. As a general hint, I would get the position of the mouse in page coordinates on hover and reposition the toolbar. Of course, I would prevent the toolbar to update its position on `editorInteraction` event.

Hope that helps.

Thanks,
