### ISSUE TITLE
Font size drop down is not updated.

### ISSUE THREAD

**Issue by qasid** [liferay/alloy-editor#584]
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/18445645/18003369/a26637f2-6ba6-11e6-9ae7-7b741c706f00.gif)

 **Steps**

1. Follow steps 1-6 as mentioned in [(#548)](https://github.com/liferay/alloy-editor/issues/548)
2. Select all text.
3. Apply font size.
4. Font size drop down value is updated.
5. Select a section of text.
6. Increment Font size.

**Expected result**
Font size drop down is updated.

**Actual result**
Font size drop down is not updated.

**Comment by ipeychev** [comment]
Hello,

Let me /cc @jbalsas here.

**Comment by jbalsas** [comment]
Hey @qasid, @ipeychev 

@antoniopol06 has already been looking into this today. We hope to have a resolution in a couple of days.

**Comment by antoniopol06** [comment]
Hi @qasid 

This is the expected behaviour of the CKEditor fontsize plugin.

When you change fontsize of element, editor creates span with this font-size as style into his span. If you select this element, font´s behaviour iterates over his parents nodes to find some span with fontsize value that it exist into list values. You can see that [in this part of code of font CkEditor plugin](https://github.com/ckeditor/ckeditor-dev/blob/master/plugins/font/plugin.js#L129-L148) and you can see the behaviour in the following gif:

![ckeditor_font](https://cloud.githubusercontent.com/assets/3017821/18081761/13193812-6e9c-11e6-91a1-a3f1756526bc.gif)

Unfortunately, there's not much more we can do at this point... You could try to file a bug report to CKEditor to see if they're willing to change it.

Thanks!
