### ISSUE TITLE
IE 11 image not resize

### ISSUE THREAD

**Issue by Patr56** [liferay/alloy-editor#596]
On ie11 and win 7, I cant resize image. Resize borders disappearing after click on image.

**Comment by ipeychev** [comment]
Hey @jbalsas, could you take a look, please?

Thanks,

**Comment by jbalsas** [comment]
Hey, @antoniopol06 was already looking into this, but so far we haven't been able to figure out the issue :(

**Comment by jbalsas** [comment]
We've been looking into this and we think we have a solution. We'll be bringing in a different image resize plugin for usage in IE and configure it automatically.

I was going to schedule for `1.3.0`, but @Patr56 just beat me to it 😉

**Comment by jbalsas** [comment]
Hey @ipeychev, @antoniopol06, the fix for this issue introduces a major breaking change as evidenced in [this commit](https://github.com/liferay/alloy-editor/commit/dbfe40614066b14c9ee6690c39b697f876b1bf64)

This will break anyone adding additional plugins. We should probably keep `value` and make the change somewhere else... what do you think?

**Comment by ipeychev** [comment]
Yeah, true. Please think about that with Antonio.
