### ISSUE TITLE
Translation in the table creation popup

### ISSUE THREAD

**Issue by Kilhog** [liferay/alloy-editor#619]
Hi, I can't find how translate "Rows" and "Cols" in the following popup :
![capture d ecran 2016-11-08 a 13 58 06](https://cloud.githubusercontent.com/assets/4045682/20099973/68d46fa0-a5bb-11e6-91d8-f6b88cd85560.png)
I try add a line "rows": "Lignes" in lang/fr.js and in lang/alloy-editor/fr.js but I doesn't work. Every other translation work great.

Have you an idea ?

**Comment by jbalsas** [comment]
Hey @Kilhog, this seems like a mistake on our side, since those labels are hardcoded and not configurable:

https://github.com/jbalsas/alloy-editor/blob/master/src/ui/react/src/components/buttons/button-table-edit.jsx#L154
https://github.com/jbalsas/alloy-editor/blob/master/src/ui/react/src/components/buttons/button-table-edit.jsx#L159

It should be easy enough to fix, adding to our next milestone.

Thanks for reporting!

**Comment by Kilhog** [comment]
Thank's 😄
