### ISSUE TITLE
Text format is not retained for copy+paste text from excel

### ISSUE THREAD

**Issue by sharmamahesh** [liferay/alloy-editor#651]
Hi,
When i copy and paste some text from excel which is having some formatting in it like(bold,italic,underline etc.)to the alloy editor, the formatting is not preserved.

For Chrome and Firefox it is not working but for IE it is working. I have attached excel file and screen shots for reference.
![firefox_paste_frm_excel](https://cloud.githubusercontent.com/assets/22740015/20970082/e5237576-bcb1-11e6-8fed-01ced7a256af.png)
![ie_11_paste_frm_excel](https://cloud.githubusercontent.com/assets/22740015/20970083/e52ecfc0-bcb1-11e6-9ca0-c7d342b461c0.png)
![chrome_paste_frm_excel](https://cloud.githubusercontent.com/assets/22740015/20970084/e5399fcc-bcb1-11e6-9131-43330206c9cd.png)
[Test.xlsx](https://github.com/liferay/alloy-editor/files/636738/Test.xlsx)

**Comment by ipeychev** [comment]
Hey @sharmamahesh,

On this feature we rely on CKEditor's implementation. There are not many things which we can do. You may check on CKEditor's site if it behaves the same. If yes, then you may report that to them, otherwise please tell us and we will find the reason and fix the issue.

For the record, you cannot expect pasting from Word/Excel to preserve everything. There are several challenges. First of all, there is not a single way to make a text bold or italic. At least three are available - `<strong>` element, `<b>` element, or with CSS. Apart from that, Excel and Word generate, let's say "interesting" HTML code. CKEditor tries to clean it, but it is not always possible.

Hope that helps,

**Comment by ipeychev** [comment]
Closing the issue, since it is related to CKEditor's engine
