### ISSUE TITLE
Get rid of frame box around pasted link

### ISSUE THREAD

**Issue by JiriZidek** [liferay/alloy-editor#659]
After pasting to editor URL as normal text - like: `https://www.seznam.cz/`
Editor adds surrounding div and some specific data- attributes -like:
`<div data-ae-embed-url="https://www.seznam.cz/"><a href="https://www.seznam.cz/" data-iframely-url="//cdn.iframe.ly/PzPVfT">Seznam - najdu tam, co neznám</a><script src="//cdn.iframe.ly/embed.js" charset="utf-8" async=""></script></div>`
Is there a way, how to disable this behavior, so pasting would result as just plain text ? 
Maybe it's more FK feature.

**Comment by jbalsas** [comment]
Hey @JiriZidek, this is the behaviour of the `ae_embed` plugin. If you paste a media url, like youtube, twitter... it will try to convert it to some kind of multimedia shareable object using the https://iframely.com/ service.

I've marked it as a bug, since it doesn't make sense to wrap it for a simple url that has no embed equivalent, but in the meantime, and if you're not using the feature, you can try disabling the `ae_embed` plugin.

**Comment by JiriZidek** [comment]
Thankx for tip @jbalsas ! Since I do not know how to "disable" the ae-embed plugin, I modified REGEX_HTTP definition on line 4504 (I use alloy-editor-no-react.js) to not find text trigger for embed plugin when pasting:

`var REGEX_HTTP = /^NO-WAY-https?/; `

It works for my purporse, but I consider this to be temporary workaround. I also changed this in minified version. I use 1.3.0.

Eventually this bug gets corrected, I'll use official release.

**Comment by antoniopol06** [comment]
hi @JiriZidek !

If you dont use ae-embed plugin, you can add 'ae_embed' into removePlugins conf to disable it.

`

    AlloyEditor.editable('myContentEditable',{
          removePlugins: AlloyEditor.Core.ATTRS.removePlugins.value + ',ae_embed'
    });

`

We will work on this issue.

Thanks for reporting this issue.
