### ISSUE TITLE
Linking relative urls

### ISSUE THREAD

**Issue by HelloZeroNet** [liferay/alloy-editor#661]
I try to add a "?Postid:32" link to a text, but the url editor turns it to "http://?Postid:32"

After it's created re-editing the link and removing the http:// works.

**Comment by ipeychev** [comment]
By default it does add the URI scheme, since in the common case that is the expected behavior. There is an option - "appendProtocol" (Boolean) which you may pass to `ButtonLinkEdit`. Setting it to `false` will disable adding the scheme. Please look how [here](http://alloyeditor.com/guides/editor_configuration/button_configuration/). The name of the button is 'linkEdit'.

Thanks,

**Comment by duracell80** [comment]
This is bad UX ... "By default it does add the URI scheme, since in the common case that is the expected behavior". What that does is ensure user frustration as HelloZeroNet suggests. The most common protocol should be provided as the place holder so that it can be deleted in order to add a relative link first time (rather than two attempts). 

No user needs a place holder in a text box that explains "type your text here".
