### ISSUE TITLE
Strore image as base64 inline 

### ISSUE THREAD

**Issue by thanhthang20** [liferay/alloy-editor#662]
Strore image as base64 inline is not a good idea. Is there anyway to store a link to remote image?.
Likely this editor is working: https://www.froala.com/wysiwyg-editor/examples/custom-image-button

**Comment by ipeychev** [comment]
Once the image is added, you may upload it to some server and replace the image src with the link to the uploaded image.

There are already asked questions about that - [here](https://github.com/liferay/alloy-editor/issues/453), [here](https://github.com/liferay/alloy-editor/issues/289) and [here](https://github.com/liferay/alloy-editor/issues/588). In the links there are more details.

**Comment by jbalsas** [comment]
For additional reference, since it doesn't appear in the other issues, you can also check our solution for it [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-editor/frontend-editor-alloyeditor-web/src/main/resources/META-INF/resources/js/editor_image_uploader.js).

What we do is:
- [Listen to the `imageAdd` event](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-editor/frontend-editor-alloyeditor-web/src/main/resources/META-INF/resources/js/editor_image_uploader.js#L53).
- On `imageAdd`, [mark the image](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-editor/frontend-editor-alloyeditor-web/src/main/resources/META-INF/resources/js/editor_image_uploader.js#L150-L152) inside the editor as "upload in progress".
- [Start uploading the image](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-editor/frontend-editor-alloyeditor-web/src/main/resources/META-INF/resources/js/editor_image_uploader.js#L164)
- When the upload is complete, [remove the upload mark](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-editor/frontend-editor-alloyeditor-web/src/main/resources/META-INF/resources/js/editor_image_uploader.js#L187_L188) on the image and [replace the base64 data for the uploaded url](https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-editor/frontend-editor-alloyeditor-web/src/main/resources/META-INF/resources/js/editor_image_uploader.js#L196)

**Comment by thanhthang20** [comment]
Really useful, thanks all.

**Comment by hew** [comment]
For those encountering this issue, depending on what version of Alloy Editor you are on, the `data` object in the code above will be undefined. 

I cloned down the repo and the latest version works fine, but on, for example, `v0.7.5`, it will not work.

**Comment by ipeychev** [comment]
Yeah, please upgrade to version > 1, preferable the latest one. We don't provide support to versions below 1. See [Semantic Versioning](http://semver.org/) for more information.

**Comment by lpsBetty** [comment]
@jbalsas Your links from your last comment aren't working anymore :/ https://github.com/liferay/alloy-editor/issues/662#issuecomment-269747013

**Comment by jbalsas** [comment]
Thanks for the heads up @lpsBetty, I've just updated the links to a more stable `7.0.x` branch.

**Comment by duracell80** [comment]
Has this ever been opened as an LPS for Liferay?

Some of our users have been "pasting" images into the editor that then don't make it into Documents and Media. I can go ahead and open an LPS or push through LESA but we could be overloading LESA?

**Comment by jbalsas** [comment]
Hey @duracell80, Liferay [relies on the `imageAdd` event](https://github.com/jbalsas/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-alloyeditor-web/src/main/resources/META-INF/resources/js/editor_image_uploader.js#L58) to trigger the external upload.

From your comment, I understand that your users have been somewhat selecting an image from some application or web site, and successfully pasting from the clipboard into the editor?

If that's the case, I think we could open a feature request here in AlloyEditor to make sure that we fire the event consistently whenever an image is added, so the image upload logic will trigger for those cases as well.
