### ISSUE TITLE
Plugin dialogs scroll page on close

### ISSUE THREAD

**Issue by wenneberg6** [liferay/alloy-editor#676]
In combination with Alloy, we are using several CKeditor plugins with dialogs, image etc. 
We have plenty of text which creates long pages. When scrolled down and interacting with a dialog we experience scrolling issues.

When a dialog is opened the editor looses focus, and when the dialog is closed the editor regains focus, but it also makes the page scroll up. 

This is not reproducable in your example page as there are no dialogs. 
I am not even sure if this is an Alloy bug or CKeditor. In the CKeditor inline example http://sdk.ckeditor.com/samples/inline.html, some similar behaviour can be noticed when closing a dialog.

![scrollprob](https://cloud.githubusercontent.com/assets/3601169/21973364/650da09a-dbc0-11e6-8ab1-c36fe158ef0c.gif)

**Comment by ipeychev** [comment]
Hey @wenneberg6,

This is an issue in CKEditor. The bug is with Chrome, in FF for example it works fine. There are people [reporting](http://stackoverflow.com/questions/39009398/prevent-scroll-jumping-in-ckeditor-and-tinymce-inline-editors-on-chrome-on-dialo) the same separately.

I'd suggest to open an issue in CKEdiror's issue [tracker](http://dev.ckeditor.com/wiki/Bugs). We provide limited support for the behaviour of their dialogs and plugins - if they break somehow in AlloyEditor, we would take a look, but if they break in CKEditor itself, we won't.

When you open the issue [there](http://dev.ckeditor.com/wiki/Bugs), could you please reference it here, so we would track it too?

Thanks,

**Comment by wenneberg6** [comment]
Apparently an open issue already exists: http://dev.ckeditor.com/ticket/14860
Thanks.

**Comment by wincent** [comment]
By way of "spring cleaning", I'm closing issues tagged with "question" that haven't had any activity in > 12 months. There have been quite a few releases since then and much has changed, and these "stale" issues are extremely unlikely to be acted on. Please feel free to comment and we can re-open on a case-by-case basis.
