### ISSUE TITLE
Table spacing is difficult to use

### ISSUE THREAD

**Issue by antoniopol06** [liferay/alloy-editor#694]
While you are typing in the first column, the rest of column are narrowing and there are times that it is difficult to use it.

![captura de pantalla 2017-02-09 a las 11 54 15](https://cloud.githubusercontent.com/assets/3017821/22780293/837d6482-eebe-11e6-9941-e862c1d38421.png)

**Comment by andrerom** [comment]
Solution to this is simple, make sure there is padding on each cell (td & th).

**Comment by duracell80** [comment]
Any updates on this? This is being reported by our DXP users as a UX concern.

![tables-hard-to-edit](https://user-images.githubusercontent.com/18121278/39781207-2aad586e-52d4-11e8-9f2c-1bef72fd93d0.gif)

**Comment by wincent** [comment]
Doing some "spring cleaning" by closing issues that were opened in 2017 — much has changed since then and there have been many releases, so there is a risk that these older issues have grown very stale and are very unlikely to be acted upon. Please feel free to commend and we can look at re-opening on a case-by-case basis.
