### ISSUE TITLE
Placeholder Text Not working with multiline text

### ISSUE THREAD

**Issue by charliecliff** [liferay/alloy-editor#697]
Placeholder Text does not work when the it's longer than a single line and overlaps any elements below the elements that have your script applied to them.

**Comment by ipeychev** [comment]
Could you please add some steps for reproducing the issue?

**Comment by wincent** [comment]
Doing some "spring cleaning" by closing issues that were opened in 2017 — much has changed since then and there have been many releases, so there is a risk that these older issues have grown very stale and are very unlikely to be acted upon. Please feel free to commend and we can look at re-opening on a case-by-case basis.
