### ISSUE TITLE
CSS :empty Selector get ignored is I apply your script to the element

### ISSUE THREAD

**Issue by charliecliff** [liferay/alloy-editor#698]
What are you doing!?

**Comment by ipeychev** [comment]
Hello,

I'm not quite sure I understand the issue, sorry. Could you please provide some steps for reproducing the issue, some screenshots, if that would help, etc.

Thanks,

**Comment by wincent** [comment]
Doing some "spring cleaning" by closing issues that were opened in 2017 — much has changed since then and there have been many releases, so there is a risk that these older issues have grown very stale and are very unlikely to be acted upon. Please feel free to commend and we can look at re-opening on a case-by-case basis.
