### ISSUE TITLE
Cannot Change Border Color

### ISSUE THREAD

**Issue by charliecliff** [liferay/alloy-editor#701]
I cannot change the Border Color that appears when I click the ADD Menu Buttons, seen here.

Where is that color set?

**Comment by ipeychev** [comment]
If you mean the border which appears on `focus`, here is how to change it:
<img width="1612" alt="screen shot 2017-03-01 at 10 45 51" src="https://cloud.githubusercontent.com/assets/78014/23454399/6297bb92-fe6c-11e6-8d42-e6b437fc940d.png">

**Comment by wincent** [comment]
By way of "spring cleaning", I'm closing issues tagged with "question" that haven't had any activity in > 12 months. There have been quite a few releases since then and much has changed, and these "stale" issues are extremely unlikely to be acted on. Please feel free to comment and we can re-open on a case-by-case basis.
