### ISSUE TITLE
Append protocol is not added to URL by default when link is edited.

### ISSUE THREAD

**Issue by antoniopol06** [liferay/alloy-editor#711]
Default value of appendProtocol is true and It works when you create a new link, although, if you edit a link and remove the protocol and you save it, the link will be updated without appendProtocol.

**Comment by jbalsas** [comment]
Hey @antoniopol06, there are no tests at all for when `appendProtocol` is false. Could you please add some? Also, the `update` tests should match closer those of the `create`. For instance, we're not checking what happens if the updated link has a protocol already, which we are doing in the create portion.

Could you add those an top of this?

Thanks!
