### ISSUE TITLE
Inserting or updating link will scroll to the top of the editor

### ISSUE THREAD

**Issue by himphen** [liferay/alloy-editor#743]
When I try to insert or update link using ButtonLinkEdit, the screen will be scrolled to the top of the editor.

**Comment by wincent** [comment]
Doing some "spring cleaning" by closing issues that were opened in 2017 — much has changed since then and there have been many releases, so there is a risk that these older issues have grown very stale and are very unlikely to be acted upon. Please feel free to commend and we can look at re-opening on a case-by-case basis.
