### ISSUE TITLE
Colorbutton Plugin: Unable to scroll after changing color of text

### ISSUE THREAD

**Issue by jaffnae** [liferay/alloy-editor#749]
This is in reference to the original bug I raised #737 
There used to be an error in the JS console which has now been fixed. Unfortunately the functional reason which caused me to raise the original bug in the first place still exists. When the content is long enough to create a scroll bar, the scroll bar disappears and I am unable to scroll anymore after changing the text color. 

I have updated the temp site ([https://tempapp53.herokuapp.com/](https://tempapp53.herokuapp.com/)) I provided in the original bug to have long content to force a scroll bar. I am using Chrome (57.0.2987.133) on MacOS Sierra. 

After changing the text colour, I am not able to scroll up or down.

**Comment by jbalsas** [comment]
Thanks @jaffnae, sorry we didn't catch that. I've verified the issue happens in the demo and not in a standalone CKEditor one, which is weird...

I'm adding this bug for our next milestone

**Comment by jaffnae** [comment]
Thanks. If it helps, it appears the scrolling gets locked as soon as you've clicked the ColorButton button in the toolbar (i.e. you don't actually have to select a color from the palette to lock up the scrolling).

**Comment by jaffnae** [comment]
Hello, just wondering whether there are any updates on this issue?

**Comment by ipeychev** [comment]
Hello,

The problem is in Color Button itself and in more details, [here](https://github.com/ckeditor/ckeditor-dev/blob/d4c35f42048233c5ec20c9b45e92250a75c92736/plugins/colorbutton/plugin.js#L115). It explicitly sets `overflow:hidden` to the body.
Since this is a third party button, better report this and fix it by yourself. Looking at the code, remove this `overflow:hidden` maybe [here](https://github.com/ckeditor/ckeditor-dev/blob/d4c35f42048233c5ec20c9b45e92250a75c92736/plugins/colorbutton/plugin.js#L206) or [here](https://github.com/ckeditor/ckeditor-dev/blob/d4c35f42048233c5ec20c9b45e92250a75c92736/plugins/colorbutton/plugin.js#L229), whichever works.

Thanks,

**Comment by ipeychev** [comment]
(Please reopen if my assumptions were wrong)
