### ISSUE TITLE
Link plugin in Bootstrap modal, input not selected

### ISSUE THREAD

**Issue by wenneberg6** [liferay/alloy-editor#750]
Hey there.

We are using an instance of Alloy inside a Bootstrap modal, but the Link plugin does not work properly.
The input field  is not focused by default and you can't add a cursor.

This is only happening inside a modal. 

![modallinkbug](https://cloud.githubusercontent.com/assets/3601169/26443457/c07e712e-4138-11e7-9c45-83f06f9c2158.gif)

Do you guys have any ideas ? or maybe a path to better debug this. 

Thanks.

**Comment by ipeychev** [comment]
Hello,

Hm, that is odd. You may play with z-index, since it is Modal. Maybe try to set explicitly z-index to the Toolbar, or to the input... this is shot in the dark, however.
You may also create a simple page to reproduce the error and we will take a look.

Thanks,

**Comment by wincent** [comment]
Doing some "spring cleaning" by closing issues that were opened in 2017 — much has changed since then and there have been many releases, so there is a risk that these older issues have grown very stale and are very unlikely to be acted upon. Please feel free to commend and we can look at re-opening on a case-by-case basis.
