### ISSUE TITLE
Cannot select multiple table cells in Chrome/Safari

### ISSUE THREAD

**Issue by andrerom** [liferay/alloy-editor#758]
1. In Chrome & Safari _(not tested in Edge)_ it's not possible to select several cells like in Firefox
2. Merge cells should be disabled when nothing is selected, it does nothing _(also see #759)_
3. Delete cells should not be plural when not several cells are selected.

------
Browsers:
- Safari 10.1
- Chrome 59
- Firefox 54

**Comment by wincent** [comment]
Verified that this is still the case in current master: selecting multiple cells works in Firefox, but not in Chrome. Testing the CKEditor v4 demo, selecting multiple cells does work in Chrome.

**Comment by wincent** [comment]
Doing some "spring cleaning" by closing issues that were opened in 2017 — much has changed since then and there have been many releases, so there is a risk that these older issues have grown very stale and are very unlikely to be acted upon. Please feel free to commend and we can look at re-opening on a case-by-case basis.
