### ISSUE TITLE
Pasting links into content area fails

### ISSUE THREAD

**Issue by wenneberg6** [liferay/alloy-editor#761]
Hey guys.
We experience an issue pasting links into the editor.

What:
Pasting a link into the editor creates a js exception and link is not inserted into content. 

Where:
Alloy v. 1.3.1 without React included
React v. 15.4.1, also tested in 15.6.1

I have recreated the issue on your current live demo and attached a gif.

In the gif i am pasting two links. 
First: http://alloyeditor.com/demo/ - fails completely and no link is inserted. 
Second: https://github.com/liferay/alloy-editor/issues - gets inserted but still cast the exception.

![alloy-link-issue](https://user-images.githubusercontent.com/3601169/27626645-0ebff482-5be9-11e7-84eb-b88c859ff3a2.gif)

**Comment by ipeychev** [comment]
About the first link, the provider didn't respond with 200, so there isn't that much to do from our side.
About the second one, on which browser is this? Because on my Chrome Version 59.0.3071.115 (Official Build) (64-bit) it doesn't happen?

**Comment by wenneberg6** [comment]
I am on the latest version of Chrome: Version 59.0.3071.115 (Officiel version) (64-bit)

Provider didn't respond ? The first link is to your own demo page, which is very much available ?

Question: Do a link have to respond 200, to be able to paste into AlloyEditor ?

**Comment by ipeychev** [comment]
Probably the second failure is a consequence of the first one, because if I just open the demo page and paste the second link, it doesn't happen.

About the provider - on the demo page the oEmbed plugin in included, which embeds content into the page. For example, if what you pasted was a YouTube URL, it would embed the video. If you disable this plugin, the link would be pasted as a raw link.
In the case you describe, the response is 417, that's why it doesn't do what is expected, sorry. We were experiencing some issues with the hosting, now we know about another one, thanks for the heads up.

Please look below for the reponse:

<img width="1616" alt="screen shot 2017-06-30 at 07 47 15" src="https://user-images.githubusercontent.com/78014/27722575-d1a0629a-5d68-11e7-8b62-fc0cf20c3f89.png">

**Comment by wenneberg6** [comment]
True, if i skip the first link, it works without the exceptions.

Regarding my question from above: Do a link have to respond 200, to be able to paste into AlloyEditor ?
In our product, we create content(including links) before the pages are published. Is it not possible to link to a page that returns 404 ?

**Comment by ipeychev** [comment]
Again - if the oEmbed plugin is included, as in this Demo page, pasting link does not just paste links. It makes a request to an external service and if a valid embeddable content is returned, it will be embedded successfullly into the page.

If the plugin is not enabled, you may paste arbitrary links, no request will be made and the editor doesn't care if they point to a valid domain, or to a valid domain, which returns 404 or if they are completely invalid links.
It is the same if you make a selection, click on link button and type: `www.....werqwrw....sd.com`. This will be accepted as a link, despite it is a junk, because the editor doesn't validate them - it is responsability of the content creator.

**Comment by wenneberg6** [comment]
Alright, thanks

**Comment by jbalsas** [comment]
Hey @ipeychev, @wenneberg6, I think this is actually a bug... we probably need to have a better error handling.

As @ipeychev explained, we do a request to try to get an embed content when the embed plugin is on. In theory, if it doesn't return a proper content, we should be simply pasting the link, so this is definitely something we need to address.

**Comment by KeKe-Li** [comment]
maybe you should write this project steps in readme ，and how can i run the project
