### ISSUE TITLE
Twitter Cards can't be Embedded

### ISSUE THREAD

**Issue by ahmattox** [liferay/alloy-editor#762]
Embedding twitter cards is broken. After pasting a twitter url into the field of the built in embed toolbar, rather than the embedded tweet (as expected) the url alone is inserted into the content.

This seems related to this change https://github.com/liferay/alloy-editor/commit/d8f3f7106a861ff0a88ff99ae176ad249df77cd4 , which removes any embedded content which contains a link.

**Comment by wincent** [comment]
Doing some "spring cleaning" by closing issues that were opened in 2017 — much has changed since then and there have been many releases, so there is a risk that these older issues have grown very stale and are very unlikely to be acted upon. Please feel free to commend and we can look at re-opening on a case-by-case basis.
