### ISSUE TITLE
Mixed Content error: http://alloy.iframe.ly/api/oembed ( load video from youtube )

### ISSUE THREAD

**Issue by epodgaetskiy** [liferay/alloy-editor#763]
Mixed Content: The page at 'https://mysite' was loaded over HTTPS, but requested an insecure script 'http://alloy.iframe.ly/api/oembed?url=https%3A%2F%2Fyoutu.be%2FhCO3Yka76IE&callback=CKEDITOR._.jsonpCallbacks[17]'. This request has been blocked; the content must be served over HTTPS.

I tried add "meta http-equiv="Content-Security-Policy" content="script-src  http://alloy.iframe.ly"", but it don't help...

**Comment by Tuubz** [comment]
+1

**Comment by jbalsas** [comment]
Hey @epodgaetskiy, @Tuubz, please see https://github.com/liferay/alloy-editor/issues/732 for some additional context on this.

The embed functionality as it is, it's just configured for demo purposes. If you want to use it in production, you should be contacting https://iframely.com/ to obtain an endpoint to use in your applications.

Based on this, it might make sense that we disable the plugin by default so it is more clear that you need to take some additional steps to have it working on your https-enabled production site.

@ipeychev?

**Comment by wincent** [comment]
Doing some "spring cleaning" by closing issues that were opened in 2017 — much has changed since then and there have been many releases, so there is a risk that these older issues have grown very stale and are very unlikely to be acted upon. Please feel free to commend and we can look at re-opening on a case-by-case basis.
