### ISSUE TITLE
Image Center Alignment

### ISSUE THREAD

**Issue by jaffnae** [liferay/alloy-editor#766]
Whenever I center-align an image, the following CSS is added:
`margin-left: 50%;
transform: translateX(-50%);`

I'd like to instead center an image in a similar way that **paragraphCenter** works. Is it possible to customize or change the behaviour of **imageCenter** button?

I've tried adding paragraphCenter into the toolbars but it still adds the above style onto the image. 

(Background info: the HTML generated inside Alloy Editor can end up inside an HTML email and most email clients do not pick up the _transform: translateX(-50%);_ CSS correctly).

**Comment by vbence86** [comment]
As the preliminary station of moving towards a more flexible way to align elements, we've first updated the default code for center-alignment. With that, the `transform` attribute is no longer employed and we solely use `margin-left` and `margin-right` to achieve the same behaviour. 

We've tested it against the major email rendering engines and it looks like a more standard and reliable solution since the majority of them display the image properly.

For further information please check out the Pull Request https://github.com/liferay/alloy-editor/pull/788. 

Looking forward, we are aiming to provide more freedom for developers to specify how command are executed and how they alter the selected markup.

**Comment by wincent** [comment]
By way of "spring cleaning", I'm closing issues tagged with "question" that haven't had any activity in > 12 months. There have been quite a few releases since then and much has changed, and these "stale" issues are extremely unlikely to be acted on. Please feel free to comment and we can re-open on a case-by-case basis.
