### ISSUE TITLE
Place-holders not showing anymore (after upgrading from v1.2.5 to v1.4.1)

### ISSUE THREAD

**Issue by Tuubz** [liferay/alloy-editor#768]

**Comment by Tuubz** [comment]
add "ae-placeholder" to class

**Comment by jbalsas** [comment]
Hey @Tuubz, we'll take a look at this for our next milestone. Could you add some additional steps to know how to test for it? It's hard to tell just from the description.

Thanks!

**Comment by vbence86** [comment]
The fix is implemented and the related Pull Request created - https://github.com/liferay/alloy-editor/pull/789.

**Comment by vbence86** [comment]
#### Steps to reproduce 
1. Add content and transforms it into `<h1>` or `<h2>` element. 
2. Empty the content of the header element. 
3. Placeholder message does NOT appear anymore since these tags are not deemed as elements that can potentially be empty.

**Comment by wincent** [comment]
Doing some "spring cleaning" by closing issues that were opened in 2017 — much has changed since then and there have been many releases, so there is a risk that these older issues have grown very stale and are very unlikely to be acted upon. Please feel free to commend and we can look at re-opening on a case-by-case basis.
