### ISSUE TITLE
Is it possible to 'exclude' certain content from being editable inside Alloy Editor?

### ISSUE THREAD

**Issue by jaffnae** [liferay/alloy-editor#806]
I've got a block of editable content which I initialise Alloy Editor object against - the entire contents of that block become editable. Is it possible to exclude certain content inside this block from being editable while the rest of the content around it is able to be edited?

**Comment by jbalsas** [comment]
Hey @jaffnae, you should be able to do that by setting the attribute `contenteditable="false"` in the nodes you don't want to be editable.

**Comment by wincent** [comment]
By way of "spring cleaning", I'm closing issues tagged with "question" that haven't had any activity in > 12 months. There have been quite a few releases since then and much has changed, and these "stale" issues are extremely unlikely to be acted on. Please feel free to comment and we can re-open on a case-by-case basis.
