### ISSUE TITLE
Replace textarea with alloy editor

### ISSUE THREAD

**Issue by moresites** [liferay/alloy-editor#865]
How to replace textarea with alloy editor and set auto-update textarea value after finish editing?

**Comment by wincent** [comment]
By way of "spring cleaning", I'm closing issues tagged with "question" that haven't had any activity in > 12 months. There have been quite a few releases since then and much has changed, and these "stale" issues are extremely unlikely to be acted on. Please feel free to comment and we can re-open on a case-by-case basis.
