### ISSUE TITLE
Add-button scrolls along

### ISSUE THREAD

**Issue by bettysteger** [liferay/alloy-editor#881]
I saw in the Demo that the "Add-button" from the `ToolbarAdd` is positioned absolute to the `body` and it stays at the selection when scrolling. 

I have 2 fixed divs, and in one the alloy editor lives - this happens when scrolling:

![alloy-editor](https://user-images.githubusercontent.com/244475/45651655-5498d200-bad2-11e8-8bff-3c803fa9f74c.gif)

I think the body CSS is causing the problem: 

```
body {
  height: calc(100% - #{$navbar-height});
  margin-top: $navbar-height; // fixed navbar
  overflow: hidden;
}
```

I have tried different elements for `uiNode` in the config to set the parent element, but no success. Sometimes the Add-button is vertically off for a few pixels (can be the `margin-top` of the body, because of the fixed navbar).

Has anyone got some recommendations how I can fix this?

**Comment by jbalsas** [comment]
Hey @lpsBetty, we have indeed faced this, and as far as I can tell, we've fixed it with a combination of usage of `uiNode` and some css to make sure the containing node has dimensions so that the add button scrolls with it.

If you could provide a codepen or a working sample of your exact setup, we might be able to take a closer look.

**Comment by bettysteger** [comment]
i managed to move the scrollbar back to the body - so this can be closed!
