### ISSUE TITLE
If AlloyEditor is Present, Drag&Drop Should Work Only Within the Editor

### ISSUE THREAD

**Issue by brianikim** [liferay/alloy-editor#903]
## Prelude
The current behavior in the portal is that drag&drop of media content (such as images and videos) onto the browser will open the content in the browser. This behavior becomes problematic when you initiate a a drag&drop of the content within something such as a Web Content. All work will be lost (if the work has not been saved) if a user does not the drop the content within the editable areas of the editor as the content will be loaded in the browser.
I cannot reproduce the issue with AlloyEditor's demo, but the issue is reproducible in the portal.

## User story
As a user,
I'd like to have drag&drop only work within the editor if the editor is present
So that accidental drops of media content in non-editable areas do not trigger the default browser response to drag&drop.

## Reproduction Steps
Steps to Reproduce:
1. Make a new Basic Web Content with some edits and save
2. Choose to make more edits and then drag an image into the content
3. The image is now part of the web content and can be edited itself (moved, size changed, etc.)
4. Drag another image to the web content editor, but this time, fail to drop it in the content window (e.g., let go of the mouse button in wrong place somewhere outside the content window)
5. Browser now opens the file full screen
6. Only option is to hit back arrow in browser

Expected Results:
Drag and drop should be disabled in non-editable areas.

Actual Results:
Browser opens the file.

Let me know if you have any questions or comments.
Thank you.

**Comment by brianikim** [comment]
Proposed fix here: https://github.com/liferay/alloy-editor/pull/904

**Comment by jbalsas** [comment]
Hey @brianikim, thanks for reporting this. As I read through it, I think this is not an issue that should be address here at all.

As you show in your fix proposal #904, this is the default browser behaviour. It doesn't matter if there's an editor or not on the page. If you drag media content to any other place, work will be lost as well.

I think this would be better addressed inside Liferay Portal itself. Because we also don't want to hijack default browser behaviours completely, I think a better and more general approach might be to have a general drop listener that on drop asks for confirmation. If the user wanted to drop content on the editor, she will have the chance to stay on the page by cancelling the navigation which we can use to prevent the default behaviour.

What do you think?

**Comment by brianikim** [comment]
Hello @jbalsas ,

That definitely does make sense and would introduce flexibility to a potential solution.

Do you have any suggestions and/or fix guidance on where to implement such a drop listener in our source code?

Sincerely,
Brian Kim
