### ISSUE TITLE
Alloy Editor is Mislabeled as a WYSIWYG editor

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#936]
... Particularly in Liferay where code sanitization strips many stylistic instructions.

**Comment by julien** [comment]
Alloy Editor uses CKEditor 4 under the hood which is labelled as a battle-tested WYSIWYG HTML editor see https://ckeditor.com/ckeditor-4/ for more details.

Thanks

**Comment by duracell80** [comment]
Ah, CKEditor isn't mislabeled. Alloy however particularly in DXP strips way too much code for it to give the user a what you see is what you get experience.

Particularly as the admin theme and site theme diverge. Should I open an LPS instead?

**Comment by julien** [comment]
Concerning DXP, you can also use the other editors as described in this [article](https://dev.liferay.com/es/develop/tutorials/-/knowledge_base/7-0/modifying-an-editors-configuration), maybe one of these fits your needs better than alloy editor. You'll see that these different editors are described as _WYSIWYG_ editors.

I don't really know if the LPS is going to help, not that it would require much time, since we're just talking about changing the project's description on GitHub, but it might help you getting a more official reply.

Thanks
