### ISSUE TITLE
Offer pre-built version releases as gulp build is failing on dependencies

### ISSUE THREAD

**Issue by duracell80** [liferay/alloy-editor#938]
Building up a node environment that is capable of building alloy editor is challenging due to broken versions of dependencies. When running gulp build the editor will not build. The issue affects machines that are setup to build Liferay themes because of the need to stay at node 4.2.2 to get themes to build correctly.

Offer an archive of built releases so that customers don't need to run two different environments to build Liferay's software.

const {stringify} = require('flatted/cjs')
      ^
SyntaxError: Unexpected token {

**Comment by julien** [comment]
Hi @duracell80,

I'll have to check out Liferay themes to know why node 4.2.2 is required, but concerning alloy-editor you can easily setup a dev environment on Windows (at least Windows 10 and Windows 7).

This was tested with `node v10.13.0` and Windows 10.

1. Since the project uses `gulp-sass`, which uses `node-sass` which requires `node-gyp` you'll need to setup your Windows machine for `node-gyp`; which basically translates to 

  ```npm install --global --production windows-build-tools```

  You'll need to run this as "Administrator" in the Windows command prompt or powershell - and be sure to wait until the process terminates correctly, if you can't make this work on your machine you won't be able to install the dependencies

2. Next, be sure to checkout the `develop` branch as these changes haven't been merged into `master`yet 

3. Run `npm i` as usual to install the dependencies

4. Once the dependencies install run `gulp release` to build the required files.

If you want to download a pre-built version of alloy-editor you can also do so by visiting the [releases](https://github.com/liferay/alloy-editor/releases) page.

I hope that helps.

**Comment by wincent** [comment]
@duracell: if you are still having problems building themes would you be able to open a ticket on the [liferay-js-themes-toolkit repo](https://github.com/liferay/liferay-js-themes-toolkit)?

Hopefully @julien's instructions above help people wishing to do builds on Windows, and for those who just want the built releases they can get them with `npm install alloyeditor@$VERSION` (where `$VERSION` is the specific version you'd like to obtain) — all of the released packages contain the built files for AlloyEditor.

If there is something in the themes toolkit that is keeping you on an ancient Node version, we should discuss it over on that repo and try to get it sorted there. Certainly all the recent releases (in the v8 and v9 series) of the toolkit are intended to work with a relatively "recent" node (for example, the [CI tests run against Node v8](https://github.com/liferay/liferay-js-themes-toolkit/blob/a20ea987d20e20c828c6412dfa10ad27a292102a/.travis.yml#L10)). I believe Node 8 came out [about two years ago](https://nodejs.org/es/blog/release/v8.0.0/).
