### ISSUE TITLE
How to get the AlloyEditor version inside a Liferay 7.1 instance?

### ISSUE THREAD

**Issue by caneta** [liferay/alloy-editor#951]
On a Liferay 7.1 installation, is there a way to get the AlloyEditor version installed?

JavaScript key `AlloyEditor.version` does not exist: any other methods to get it?

Thank you.

**Comment by julien** [comment]
Hi @caneta,

As far as I know this is not available at the moment, but we could consider adding that.

Thanks for your suggestion

**Comment by jbalsas** [comment]
Hey @caneta, could you describe your end use case with a bit more of detail? I'm asking because `AlloyEditor` is not always present on a page, so there will be cases where not even `AlloyEditor` will be defined. 

What are you trying to attempt? Where do you expect to be able to detect the included editor version?

**Comment by jbalsas** [comment]
I was asking because both the `AMD Loader` and `Senna` are present at all times in the page, while `AlloyEditor` isn't.

We're currently outputting the version to the bundled file, so you could explore the `alloy-editor-no-ckeditor.min.js` file to see the file right there at the top in the meantime.

**Comment by caneta** [comment]
> I was asking because both the `AMD Loader` and `Senna` are present at all times in the page, while `AlloyEditor` isn't.

Sure, but I don't mind: I will call `AlloyEditor.version` when available...

> We're currently outputting the version to the bundled file, so you could explore the `alloy-editor-no-ckeditor.min.js` file to see the file right there at the top in the meantime.

Ok, but it's a little bit unconfortable than having a property inside a JS object.

**Comment by jbalsas** [comment]
Yeah, I was just mentioning so you'd know where to look until we implement it

**Comment by caneta** [comment]
> Yeah, I was just mentioning so you'd know where to look until we implement it

Ok, thank you so much!
